/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacion.vista;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author Usuario
 */
public class AgregarAdmin extends javax.swing.JPanel {

    /**
     * Creates new form AgregarAdmin
     */
    public AgregarAdmin() {
        initComponents();
        
        OcultarPanels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblAccion = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblMessage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        listaEntidades = new javax.swing.JComboBox<>();
        AggVcls = new javax.swing.JPanel();
        lblNumSerie = new javax.swing.JLabel();
        txtNumSerie = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblPrecio = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lblPaisP = new javax.swing.JLabel();
        txtPaisP = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        lblVersion = new javax.swing.JLabel();
        txtVersion = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        lblMotor = new javax.swing.JLabel();
        txtMotor = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        lblTrans = new javax.swing.JLabel();
        txtTrans = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        lblModelo = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        lblColor = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        btnAgregar = new javax.swing.JButton();
        lblStock = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        jSeparator56 = new javax.swing.JSeparator();
        AggVrs = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        lblNombre = new javax.swing.JLabel();
        txtPrecio1 = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        lblTransmision = new javax.swing.JLabel();
        txtTransmision = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        lblMotorMt = new javax.swing.JLabel();
        txtMotorMt = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        btnAgregarMt = new javax.swing.JButton();
        AggModelos = new javax.swing.JPanel();
        lblIdMdl = new javax.swing.JLabel();
        txtIdModelo = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        lblNombreMdl = new javax.swing.JLabel();
        txtNombreMod = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        btnAgregarMdl = new javax.swing.JButton();
        AggColors = new javax.swing.JPanel();
        btnAgregar3 = new javax.swing.JButton();
        lblIdClr = new javax.swing.JLabel();
        txtIdColor = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        lblNombreClr = new javax.swing.JLabel();
        txtNombreClr = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();
        AggEmp = new javax.swing.JPanel();
        lblIdEmp = new javax.swing.JLabel();
        txtIdEmp = new javax.swing.JTextField();
        jSeparator18 = new javax.swing.JSeparator();
        lblNombreEmp = new javax.swing.JLabel();
        txtNombreEmp = new javax.swing.JTextField();
        jSeparator19 = new javax.swing.JSeparator();
        lblApellEmp = new javax.swing.JLabel();
        txtApellEmp = new javax.swing.JTextField();
        jSeparator20 = new javax.swing.JSeparator();
        lblVersion1 = new javax.swing.JLabel();
        txtVersion1 = new javax.swing.JTextField();
        jSeparator21 = new javax.swing.JSeparator();
        lblMotor2 = new javax.swing.JLabel();
        txtMotor2 = new javax.swing.JTextField();
        jSeparator22 = new javax.swing.JSeparator();
        lblTrans2 = new javax.swing.JLabel();
        txtTrans2 = new javax.swing.JTextField();
        jSeparator23 = new javax.swing.JSeparator();
        lblModelo1 = new javax.swing.JLabel();
        txtModelo1 = new javax.swing.JTextField();
        jSeparator24 = new javax.swing.JSeparator();
        lblColor1 = new javax.swing.JLabel();
        txtColor1 = new javax.swing.JTextField();
        jSeparator25 = new javax.swing.JSeparator();
        btnAgregar4 = new javax.swing.JButton();
        lblColor2 = new javax.swing.JLabel();
        txtColor2 = new javax.swing.JTextField();
        jSeparator26 = new javax.swing.JSeparator();
        AggDept = new javax.swing.JPanel();
        btnAgregar5 = new javax.swing.JButton();
        lblId3 = new javax.swing.JLabel();
        txtIdModelo2 = new javax.swing.JTextField();
        jSeparator27 = new javax.swing.JSeparator();
        lblNombre3 = new javax.swing.JLabel();
        lblNombreMod2 = new javax.swing.JTextField();
        jSeparator28 = new javax.swing.JSeparator();
        AggDirEmp = new javax.swing.JPanel();
        lblId4 = new javax.swing.JLabel();
        txtId1 = new javax.swing.JTextField();
        jSeparator29 = new javax.swing.JSeparator();
        lblNombre4 = new javax.swing.JLabel();
        txtPrecio3 = new javax.swing.JTextField();
        jSeparator30 = new javax.swing.JSeparator();
        lblTrans3 = new javax.swing.JLabel();
        txtTrans3 = new javax.swing.JTextField();
        jSeparator31 = new javax.swing.JSeparator();
        lblMotor3 = new javax.swing.JLabel();
        txtMotor3 = new javax.swing.JTextField();
        jSeparator32 = new javax.swing.JSeparator();
        btnAgregar6 = new javax.swing.JButton();
        lblMotor4 = new javax.swing.JLabel();
        txtMotor4 = new javax.swing.JTextField();
        jSeparator33 = new javax.swing.JSeparator();
        AggCotiz = new javax.swing.JPanel();
        lblId5 = new javax.swing.JLabel();
        txtId2 = new javax.swing.JTextField();
        jSeparator34 = new javax.swing.JSeparator();
        lblNombre5 = new javax.swing.JLabel();
        txtPrecio4 = new javax.swing.JTextField();
        jSeparator35 = new javax.swing.JSeparator();
        lblTrans4 = new javax.swing.JLabel();
        txtTrans4 = new javax.swing.JTextField();
        jSeparator36 = new javax.swing.JSeparator();
        lblMotor5 = new javax.swing.JLabel();
        txtMotor5 = new javax.swing.JTextField();
        jSeparator37 = new javax.swing.JSeparator();
        btnAgregar7 = new javax.swing.JButton();
        lblMotor6 = new javax.swing.JLabel();
        txtMotor6 = new javax.swing.JTextField();
        jSeparator38 = new javax.swing.JSeparator();
        AggFacts = new javax.swing.JPanel();
        lblId6 = new javax.swing.JLabel();
        txtId3 = new javax.swing.JTextField();
        jSeparator39 = new javax.swing.JSeparator();
        lblNombre6 = new javax.swing.JLabel();
        txtPrecio5 = new javax.swing.JTextField();
        jSeparator40 = new javax.swing.JSeparator();
        lblTrans5 = new javax.swing.JLabel();
        txtTrans5 = new javax.swing.JTextField();
        jSeparator41 = new javax.swing.JSeparator();
        btnAgregar8 = new javax.swing.JButton();
        AggCli = new javax.swing.JPanel();
        lblNumSerie2 = new javax.swing.JLabel();
        txtNumSerie2 = new javax.swing.JTextField();
        jSeparator42 = new javax.swing.JSeparator();
        lblPrecio2 = new javax.swing.JLabel();
        txtPrecio6 = new javax.swing.JTextField();
        jSeparator43 = new javax.swing.JSeparator();
        lblPaisP2 = new javax.swing.JLabel();
        txtPaisP2 = new javax.swing.JTextField();
        jSeparator44 = new javax.swing.JSeparator();
        lblVersion2 = new javax.swing.JLabel();
        txtVersion2 = new javax.swing.JTextField();
        jSeparator45 = new javax.swing.JSeparator();
        lblMotor7 = new javax.swing.JLabel();
        txtMotor7 = new javax.swing.JTextField();
        jSeparator46 = new javax.swing.JSeparator();
        lblTrans6 = new javax.swing.JLabel();
        txtTrans6 = new javax.swing.JTextField();
        jSeparator47 = new javax.swing.JSeparator();
        lblModelo2 = new javax.swing.JLabel();
        txtModelo2 = new javax.swing.JTextField();
        jSeparator48 = new javax.swing.JSeparator();
        lblColor3 = new javax.swing.JLabel();
        txtColor3 = new javax.swing.JTextField();
        jSeparator49 = new javax.swing.JSeparator();
        btnAgregar9 = new javax.swing.JButton();
        lblColor4 = new javax.swing.JLabel();
        txtColor4 = new javax.swing.JTextField();
        jSeparator50 = new javax.swing.JSeparator();
        AggDirCli = new javax.swing.JPanel();
        lblId7 = new javax.swing.JLabel();
        txtId4 = new javax.swing.JTextField();
        jSeparator51 = new javax.swing.JSeparator();
        lblNombre7 = new javax.swing.JLabel();
        txtPrecio7 = new javax.swing.JTextField();
        jSeparator52 = new javax.swing.JSeparator();
        lblTrans7 = new javax.swing.JLabel();
        txtTrans7 = new javax.swing.JTextField();
        jSeparator53 = new javax.swing.JSeparator();
        lblMotor8 = new javax.swing.JLabel();
        txtMotor8 = new javax.swing.JTextField();
        jSeparator54 = new javax.swing.JSeparator();
        btnAgregar10 = new javax.swing.JButton();
        lblMotor9 = new javax.swing.JLabel();
        txtMotor9 = new javax.swing.JTextField();
        jSeparator55 = new javax.swing.JSeparator();
        lblInstruct = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 470));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAccion.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblAccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAccion.setText("Agregar");
        jPanel1.add(lblAccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 200, -1));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 10, 470));

        lblMessage.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblMessage.setForeground(new java.awt.Color(0, 193, 75));
        jPanel1.add(lblMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 450, 20));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Administrador de base de datos");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 260, 30));

        listaEntidades.setBackground(new java.awt.Color(214, 5, 5));
        listaEntidades.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        listaEntidades.setForeground(new java.awt.Color(255, 255, 255));
        listaEntidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vehículos", "Versiones", "Modelos", "Colores", "Empleados", "Departamentos", "DireccionesEmpleados", "Cotizaciones", "Facturas", "Clientes", "DireccionesClientes" }));
        listaEntidades.setBorder(new javax.swing.border.MatteBorder(null));
        listaEntidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaEntidadesActionPerformed(evt);
            }
        });
        jPanel1.add(listaEntidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 170, 40));

        AggVcls.setBackground(new java.awt.Color(255, 255, 255));
        AggVcls.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNumSerie.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblNumSerie.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNumSerie.setText("Número de serie:");
        AggVcls.add(lblNumSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 110, 30));

        txtNumSerie.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNumSerie.setBorder(null);
        AggVcls.add(txtNumSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 240, 30));
        AggVcls.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 260, 10));

        lblPrecio.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblPrecio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPrecio.setText("Precio:");
        AggVcls.add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 100, 30));

        txtPrecio.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtPrecio.setBorder(null);
        AggVcls.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 240, 30));
        AggVcls.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 260, 10));

        lblPaisP.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblPaisP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPaisP.setText("País de procedencia:");
        AggVcls.add(lblPaisP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 120, 30));

        txtPaisP.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtPaisP.setBorder(null);
        AggVcls.add(txtPaisP, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 240, 30));
        AggVcls.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 260, 10));

        lblVersion.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblVersion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblVersion.setText("Versión:");
        AggVcls.add(lblVersion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 100, 30));

        txtVersion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtVersion.setBorder(null);
        AggVcls.add(txtVersion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 240, 30));
        AggVcls.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 260, 10));

        lblMotor.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblMotor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMotor.setText("Motor:");
        AggVcls.add(lblMotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 100, 30));

        txtMotor.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtMotor.setBorder(null);
        AggVcls.add(txtMotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 240, 30));
        AggVcls.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 260, 10));

        lblTrans.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblTrans.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTrans.setText("Transmisión:");
        AggVcls.add(lblTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 100, 30));

        txtTrans.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtTrans.setBorder(null);
        AggVcls.add(txtTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 240, 30));
        AggVcls.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 260, 10));

        lblModelo.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblModelo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblModelo.setText("Modelo:");
        AggVcls.add(lblModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 50, 30));

        txtModelo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtModelo.setBorder(null);
        AggVcls.add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 120, 30));
        AggVcls.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 140, 10));

        lblColor.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblColor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblColor.setText("Color:");
        AggVcls.add(lblColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 40, 30));

        txtColor.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtColor.setBorder(null);
        AggVcls.add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 110, 30));
        AggVcls.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 130, 10));

        btnAgregar.setBackground(new java.awt.Color(214, 5, 5));
        btnAgregar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        AggVcls.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 90, 30));

        lblStock.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblStock.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStock.setText("Stock:");
        AggVcls.add(lblStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 100, 30));

        txtStock.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtStock.setBorder(null);
        AggVcls.add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 240, 30));
        AggVcls.add(jSeparator56, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 260, 10));

        jPanel1.add(AggVcls, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 490, 320));

        AggVrs.setBackground(new java.awt.Color(255, 255, 255));
        AggVrs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblId.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblId.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblId.setText("Id:");
        AggVrs.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 110, 30));

        txtId.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtId.setBorder(null);
        AggVrs.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 240, 30));
        AggVrs.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 260, 10));

        lblNombre.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombre.setText("Nombre:");
        AggVrs.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 100, 30));

        txtPrecio1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtPrecio1.setBorder(null);
        AggVrs.add(txtPrecio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 240, 30));
        AggVrs.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 260, 10));

        lblTransmision.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblTransmision.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTransmision.setText("Transmisión:");
        AggVrs.add(lblTransmision, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 120, 30));

        txtTransmision.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtTransmision.setBorder(null);
        AggVrs.add(txtTransmision, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 240, 30));
        AggVrs.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 260, 10));

        lblMotorMt.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblMotorMt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMotorMt.setText("Motor:");
        AggVrs.add(lblMotorMt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 100, 30));

        txtMotorMt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtMotorMt.setBorder(null);
        AggVrs.add(txtMotorMt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 240, 30));
        AggVrs.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 260, 10));

        btnAgregarMt.setBackground(new java.awt.Color(214, 5, 5));
        btnAgregarMt.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnAgregarMt.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarMt.setText("Agregar");
        AggVrs.add(btnAgregarMt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 90, 30));

        jPanel1.add(AggVrs, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 490, 320));

        AggModelos.setBackground(new java.awt.Color(255, 255, 255));
        AggModelos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIdMdl.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblIdMdl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIdMdl.setText("Id:");
        AggModelos.add(lblIdMdl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 110, 30));

        txtIdModelo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtIdModelo.setBorder(null);
        AggModelos.add(txtIdModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 240, 30));
        AggModelos.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 260, 10));

        lblNombreMdl.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblNombreMdl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombreMdl.setText("Nombre:");
        AggModelos.add(lblNombreMdl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 100, 30));

        txtNombreMod.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNombreMod.setBorder(null);
        AggModelos.add(txtNombreMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 240, 30));
        AggModelos.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 260, 10));

        btnAgregarMdl.setBackground(new java.awt.Color(214, 5, 5));
        btnAgregarMdl.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnAgregarMdl.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarMdl.setText("Agregar");
        AggModelos.add(btnAgregarMdl, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 90, 30));

        jPanel1.add(AggModelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 490, 320));

        AggColors.setBackground(new java.awt.Color(255, 255, 255));
        AggColors.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregar3.setBackground(new java.awt.Color(214, 5, 5));
        btnAgregar3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnAgregar3.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar3.setText("Agregar");
        AggColors.add(btnAgregar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 90, 30));

        lblIdClr.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblIdClr.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIdClr.setText("Id:");
        AggColors.add(lblIdClr, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 110, 30));

        txtIdColor.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtIdColor.setBorder(null);
        AggColors.add(txtIdColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 240, 30));
        AggColors.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 260, 10));

        lblNombreClr.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblNombreClr.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombreClr.setText("Nombre:");
        AggColors.add(lblNombreClr, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 100, 30));

        txtNombreClr.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNombreClr.setBorder(null);
        AggColors.add(txtNombreClr, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 240, 30));
        AggColors.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 260, 10));

        jPanel1.add(AggColors, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 490, 320));

        AggEmp.setBackground(new java.awt.Color(255, 255, 255));
        AggEmp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIdEmp.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblIdEmp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIdEmp.setText("Id del empleado:");
        AggEmp.add(lblIdEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 110, 30));

        txtIdEmp.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtIdEmp.setBorder(null);
        AggEmp.add(txtIdEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 240, 30));
        AggEmp.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 260, 10));

        lblNombreEmp.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblNombreEmp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombreEmp.setText("Nombre:");
        AggEmp.add(lblNombreEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 100, 30));

        txtNombreEmp.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNombreEmp.setBorder(null);
        AggEmp.add(txtNombreEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 240, 30));
        AggEmp.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 260, 10));

        lblApellEmp.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblApellEmp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblApellEmp.setText("Apellidos:");
        AggEmp.add(lblApellEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 120, 30));

        txtApellEmp.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtApellEmp.setBorder(null);
        AggEmp.add(txtApellEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 240, 30));
        AggEmp.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 260, 10));

        lblVersion1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblVersion1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblVersion1.setText("Usuario:");
        AggEmp.add(lblVersion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 100, 30));

        txtVersion1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtVersion1.setBorder(null);
        AggEmp.add(txtVersion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 240, 30));
        AggEmp.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 260, 10));

        lblMotor2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblMotor2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMotor2.setText("Contraseña:");
        AggEmp.add(lblMotor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 100, 30));

        txtMotor2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtMotor2.setBorder(null);
        AggEmp.add(txtMotor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 240, 30));
        AggEmp.add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 260, 10));

        lblTrans2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblTrans2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTrans2.setText("Comisión:");
        AggEmp.add(lblTrans2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 100, 30));

        txtTrans2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtTrans2.setBorder(null);
        AggEmp.add(txtTrans2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 240, 30));
        AggEmp.add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 260, 10));

        lblModelo1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblModelo1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblModelo1.setText("NSS:");
        AggEmp.add(lblModelo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 60, 30));

        txtModelo1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtModelo1.setBorder(null);
        AggEmp.add(txtModelo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 140, 30));
        AggEmp.add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 160, 10));

        lblColor1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblColor1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblColor1.setText("Teléfono:");
        AggEmp.add(lblColor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 60, 30));

        txtColor1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtColor1.setBorder(null);
        AggEmp.add(txtColor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 140, 30));
        AggEmp.add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 160, 10));

        btnAgregar4.setBackground(new java.awt.Color(214, 5, 5));
        btnAgregar4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnAgregar4.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar4.setText("Agregar");
        AggEmp.add(btnAgregar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 90, 30));

        lblColor2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblColor2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblColor2.setText("Correo:");
        AggEmp.add(lblColor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 100, 30));

        txtColor2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtColor2.setBorder(null);
        AggEmp.add(txtColor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 220, 30));
        AggEmp.add(jSeparator26, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 240, 10));

        jPanel1.add(AggEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 490, 320));

        AggDept.setBackground(new java.awt.Color(255, 255, 255));
        AggDept.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregar5.setBackground(new java.awt.Color(214, 5, 5));
        btnAgregar5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnAgregar5.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar5.setText("Agregar");
        AggDept.add(btnAgregar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 90, 30));

        lblId3.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblId3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblId3.setText("Id del Departamento:");
        AggDept.add(lblId3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 120, 30));

        txtIdModelo2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtIdModelo2.setBorder(null);
        AggDept.add(txtIdModelo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 240, 30));
        AggDept.add(jSeparator27, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 260, 10));

        lblNombre3.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblNombre3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombre3.setText("Nombre:");
        AggDept.add(lblNombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 100, 30));

        lblNombreMod2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblNombreMod2.setBorder(null);
        AggDept.add(lblNombreMod2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 240, 30));
        AggDept.add(jSeparator28, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 260, 10));

        jPanel1.add(AggDept, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 490, 320));

        AggDirEmp.setBackground(new java.awt.Color(255, 255, 255));
        AggDirEmp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblId4.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblId4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblId4.setText("Id:");
        AggDirEmp.add(lblId4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 110, 30));

        txtId1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtId1.setBorder(null);
        AggDirEmp.add(txtId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 240, 30));
        AggDirEmp.add(jSeparator29, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 260, 10));

        lblNombre4.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblNombre4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombre4.setText("Calle:");
        AggDirEmp.add(lblNombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 70, 30));

        txtPrecio3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtPrecio3.setBorder(null);
        AggDirEmp.add(txtPrecio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 240, 30));
        AggDirEmp.add(jSeparator30, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 260, 10));

        lblTrans3.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblTrans3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTrans3.setText("Colonia:");
        AggDirEmp.add(lblTrans3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 80, 30));

        txtTrans3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtTrans3.setBorder(null);
        AggDirEmp.add(txtTrans3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 240, 30));
        AggDirEmp.add(jSeparator31, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 260, 10));

        lblMotor3.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblMotor3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMotor3.setText("Número Exterior:");
        AggDirEmp.add(lblMotor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 110, 30));

        txtMotor3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtMotor3.setBorder(null);
        AggDirEmp.add(txtMotor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 240, 30));
        AggDirEmp.add(jSeparator32, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 260, 10));

        btnAgregar6.setBackground(new java.awt.Color(214, 5, 5));
        btnAgregar6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnAgregar6.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar6.setText("Agregar");
        AggDirEmp.add(btnAgregar6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 90, 30));

        lblMotor4.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblMotor4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMotor4.setText("Código Postal:");
        AggDirEmp.add(lblMotor4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 110, 30));

        txtMotor4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtMotor4.setBorder(null);
        AggDirEmp.add(txtMotor4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 240, 30));
        AggDirEmp.add(jSeparator33, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 260, 10));

        jPanel1.add(AggDirEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 490, 320));

        AggCotiz.setBackground(new java.awt.Color(255, 255, 255));
        AggCotiz.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblId5.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblId5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblId5.setText("Id de la Cotización:");
        AggCotiz.add(lblId5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 30));

        txtId2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtId2.setBorder(null);
        AggCotiz.add(txtId2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 240, 30));
        AggCotiz.add(jSeparator34, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 260, 10));

        lblNombre5.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblNombre5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombre5.setText("Fecha de cotización:");
        AggCotiz.add(lblNombre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 120, 30));

        txtPrecio4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtPrecio4.setBorder(null);
        AggCotiz.add(txtPrecio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 240, 30));
        AggCotiz.add(jSeparator35, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 260, 10));

        lblTrans4.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblTrans4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTrans4.setText("Nombre del Usuario:");
        AggCotiz.add(lblTrans4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 120, 30));

        txtTrans4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtTrans4.setBorder(null);
        AggCotiz.add(txtTrans4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 240, 30));
        AggCotiz.add(jSeparator36, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 260, 10));

        lblMotor5.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblMotor5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMotor5.setText("Teléfono:");
        AggCotiz.add(lblMotor5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 110, 30));

        txtMotor5.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtMotor5.setBorder(null);
        AggCotiz.add(txtMotor5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 240, 30));
        AggCotiz.add(jSeparator37, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 260, 10));

        btnAgregar7.setBackground(new java.awt.Color(214, 5, 5));
        btnAgregar7.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnAgregar7.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar7.setText("Agregar");
        AggCotiz.add(btnAgregar7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 90, 30));

        lblMotor6.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblMotor6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMotor6.setText("Correo:");
        AggCotiz.add(lblMotor6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 110, 30));

        txtMotor6.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtMotor6.setBorder(null);
        AggCotiz.add(txtMotor6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 240, 30));
        AggCotiz.add(jSeparator38, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 260, 10));

        jPanel1.add(AggCotiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 490, 320));

        AggFacts.setBackground(new java.awt.Color(255, 255, 255));
        AggFacts.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblId6.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblId6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblId6.setText("Código de la factura:");
        AggFacts.add(lblId6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 30));

        txtId3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtId3.setBorder(null);
        AggFacts.add(txtId3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 240, 30));
        AggFacts.add(jSeparator39, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 260, 10));

        lblNombre6.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblNombre6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombre6.setText("Método de pago:");
        AggFacts.add(lblNombre6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 120, 30));

        txtPrecio5.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtPrecio5.setBorder(null);
        AggFacts.add(txtPrecio5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 240, 30));
        AggFacts.add(jSeparator40, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 260, 10));

        lblTrans5.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblTrans5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTrans5.setText("Fecha de venta:");
        AggFacts.add(lblTrans5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 120, 30));

        txtTrans5.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtTrans5.setBorder(null);
        AggFacts.add(txtTrans5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 240, 30));
        AggFacts.add(jSeparator41, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 260, 10));

        btnAgregar8.setBackground(new java.awt.Color(214, 5, 5));
        btnAgregar8.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnAgregar8.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar8.setText("Agregar");
        AggFacts.add(btnAgregar8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 90, 30));

        jPanel1.add(AggFacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 490, 320));

        AggCli.setBackground(new java.awt.Color(255, 255, 255));
        AggCli.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNumSerie2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblNumSerie2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNumSerie2.setText("Id del cliente:");
        AggCli.add(lblNumSerie2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 110, 30));

        txtNumSerie2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNumSerie2.setBorder(null);
        AggCli.add(txtNumSerie2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 240, 30));
        AggCli.add(jSeparator42, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 260, 10));

        lblPrecio2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblPrecio2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPrecio2.setText("Nombre:");
        AggCli.add(lblPrecio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 100, 30));

        txtPrecio6.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtPrecio6.setBorder(null);
        AggCli.add(txtPrecio6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 240, 30));
        AggCli.add(jSeparator43, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 260, 10));

        lblPaisP2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblPaisP2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPaisP2.setText("Apellidos:");
        AggCli.add(lblPaisP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 120, 30));

        txtPaisP2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtPaisP2.setBorder(null);
        AggCli.add(txtPaisP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 240, 30));
        AggCli.add(jSeparator44, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 260, 10));

        lblVersion2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblVersion2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblVersion2.setText("Sueldo:");
        AggCli.add(lblVersion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 100, 30));

        txtVersion2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtVersion2.setBorder(null);
        AggCli.add(txtVersion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 240, 30));
        AggCli.add(jSeparator45, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 260, 10));

        lblMotor7.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblMotor7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMotor7.setText("RFC:");
        AggCli.add(lblMotor7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 100, 30));

        txtMotor7.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtMotor7.setBorder(null);
        AggCli.add(txtMotor7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 240, 30));
        AggCli.add(jSeparator46, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 260, 10));

        lblTrans6.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblTrans6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTrans6.setText("Historial Crediticio:");
        AggCli.add(lblTrans6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 110, 30));

        txtTrans6.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtTrans6.setBorder(null);
        AggCli.add(txtTrans6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 240, 30));
        AggCli.add(jSeparator47, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 260, 10));

        lblModelo2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblModelo2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblModelo2.setText("Fecha de registro:");
        AggCli.add(lblModelo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 100, 30));

        txtModelo2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtModelo2.setBorder(null);
        AggCli.add(txtModelo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 120, 30));
        AggCli.add(jSeparator48, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 140, 10));

        lblColor3.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblColor3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblColor3.setText("Teléfono:");
        AggCli.add(lblColor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 60, 30));

        txtColor3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtColor3.setBorder(null);
        AggCli.add(txtColor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 140, 30));
        AggCli.add(jSeparator49, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 160, 10));

        btnAgregar9.setBackground(new java.awt.Color(214, 5, 5));
        btnAgregar9.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnAgregar9.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar9.setText("Agregar");
        AggCli.add(btnAgregar9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 90, 30));

        lblColor4.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblColor4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblColor4.setText("Correo:");
        AggCli.add(lblColor4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 100, 30));

        txtColor4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtColor4.setBorder(null);
        AggCli.add(txtColor4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 220, 30));
        AggCli.add(jSeparator50, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 240, 10));

        jPanel1.add(AggCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 490, 320));

        AggDirCli.setBackground(new java.awt.Color(255, 255, 255));
        AggDirCli.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblId7.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblId7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblId7.setText("Id:");
        AggDirCli.add(lblId7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 110, 30));

        txtId4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtId4.setBorder(null);
        AggDirCli.add(txtId4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 240, 30));
        AggDirCli.add(jSeparator51, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 260, 10));

        lblNombre7.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblNombre7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombre7.setText("Calle:");
        AggDirCli.add(lblNombre7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 70, 30));

        txtPrecio7.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtPrecio7.setBorder(null);
        AggDirCli.add(txtPrecio7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 240, 30));
        AggDirCli.add(jSeparator52, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 260, 10));

        lblTrans7.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblTrans7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTrans7.setText("Colonia:");
        AggDirCli.add(lblTrans7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 80, 30));

        txtTrans7.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtTrans7.setBorder(null);
        AggDirCli.add(txtTrans7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 240, 30));
        AggDirCli.add(jSeparator53, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 260, 10));

        lblMotor8.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblMotor8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMotor8.setText("Número Exterior:");
        AggDirCli.add(lblMotor8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 110, 30));

        txtMotor8.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtMotor8.setBorder(null);
        AggDirCli.add(txtMotor8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 240, 30));
        AggDirCli.add(jSeparator54, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 260, 10));

        btnAgregar10.setBackground(new java.awt.Color(214, 5, 5));
        btnAgregar10.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnAgregar10.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar10.setText("Agregar");
        AggDirCli.add(btnAgregar10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 90, 30));

        lblMotor9.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblMotor9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMotor9.setText("Código Postal:");
        AggDirCli.add(lblMotor9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 110, 30));

        txtMotor9.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtMotor9.setBorder(null);
        AggDirCli.add(txtMotor9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 240, 30));
        AggDirCli.add(jSeparator55, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 260, 10));

        jPanel1.add(AggDirCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 490, 320));

        lblInstruct.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblInstruct.setForeground(new java.awt.Color(153, 153, 153));
        lblInstruct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstruct.setText("Seleccione una entidad para agregar información:");
        jPanel1.add(lblInstruct, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 320, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void listaEntidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaEntidadesActionPerformed
        switch (listaEntidades.getSelectedItem().toString()) {
            case "Vehículos":
                OcultarPanels();
                AggVcls.setVisible(true);
                break;
            case "Versiones":
                OcultarPanels();
                AggVrs.setVisible(true);
                break;
            case "Modelos":
                OcultarPanels();
                AggModelos.setVisible(true);
                break;
            case "Colores":
                OcultarPanels();
                AggColors.setVisible(true);
                break;
            case "Empleados":
                OcultarPanels();
                AggEmp.setVisible(true);
                break;
            case "Departamentos":
                OcultarPanels();
                AggDept.setVisible(true);
                break;
            case "DireccionesEmpleados":
                OcultarPanels();
                AggDirEmp.setVisible(true);
                break;
            case "Cotizaciones":
                OcultarPanels();
                AggCotiz.setVisible(true);
                break;
            case "Facturas":
                OcultarPanels();
                AggFacts.setVisible(true);
                break;
            case "Clientes":
                OcultarPanels();
                AggCli.setVisible(true);
                break;
            case "DireccionesClientes":
                OcultarPanels();
                AggDirCli.setVisible(true);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_listaEntidadesActionPerformed

    private void OcultarPanels() {
        AggVcls.setVisible(false);
        AggVrs.setVisible(false);
        AggModelos.setVisible(false);
        AggColors.setVisible(false);
        AggEmp.setVisible(false);
        AggDept.setVisible(false);
        AggDirEmp.setVisible(false);
        AggCotiz.setVisible(false);
        AggFacts.setVisible(false);
        AggCli.setVisible(false);
        AggDirCli.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AggCli;
    private javax.swing.JPanel AggColors;
    private javax.swing.JPanel AggCotiz;
    public javax.swing.JPanel AggDept;
    private javax.swing.JPanel AggDirCli;
    public javax.swing.JPanel AggDirEmp;
    private javax.swing.JPanel AggEmp;
    private javax.swing.JPanel AggFacts;
    private javax.swing.JPanel AggModelos;
    private javax.swing.JPanel AggVcls;
    private javax.swing.JPanel AggVrs;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregar10;
    private javax.swing.JButton btnAgregar3;
    private javax.swing.JButton btnAgregar4;
    private javax.swing.JButton btnAgregar5;
    private javax.swing.JButton btnAgregar6;
    private javax.swing.JButton btnAgregar7;
    private javax.swing.JButton btnAgregar8;
    private javax.swing.JButton btnAgregar9;
    private javax.swing.JButton btnAgregarMdl;
    private javax.swing.JButton btnAgregarMt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator28;
    private javax.swing.JSeparator jSeparator29;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator30;
    private javax.swing.JSeparator jSeparator31;
    private javax.swing.JSeparator jSeparator32;
    private javax.swing.JSeparator jSeparator33;
    private javax.swing.JSeparator jSeparator34;
    private javax.swing.JSeparator jSeparator35;
    private javax.swing.JSeparator jSeparator36;
    private javax.swing.JSeparator jSeparator37;
    private javax.swing.JSeparator jSeparator38;
    private javax.swing.JSeparator jSeparator39;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator40;
    private javax.swing.JSeparator jSeparator41;
    private javax.swing.JSeparator jSeparator42;
    private javax.swing.JSeparator jSeparator43;
    private javax.swing.JSeparator jSeparator44;
    private javax.swing.JSeparator jSeparator45;
    private javax.swing.JSeparator jSeparator46;
    private javax.swing.JSeparator jSeparator47;
    private javax.swing.JSeparator jSeparator48;
    private javax.swing.JSeparator jSeparator49;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator50;
    private javax.swing.JSeparator jSeparator51;
    private javax.swing.JSeparator jSeparator52;
    private javax.swing.JSeparator jSeparator53;
    private javax.swing.JSeparator jSeparator54;
    private javax.swing.JSeparator jSeparator55;
    private javax.swing.JSeparator jSeparator56;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblAccion;
    private javax.swing.JLabel lblApellEmp;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblColor1;
    private javax.swing.JLabel lblColor2;
    private javax.swing.JLabel lblColor3;
    private javax.swing.JLabel lblColor4;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblId3;
    private javax.swing.JLabel lblId4;
    private javax.swing.JLabel lblId5;
    private javax.swing.JLabel lblId6;
    private javax.swing.JLabel lblId7;
    private javax.swing.JLabel lblIdClr;
    private javax.swing.JLabel lblIdEmp;
    private javax.swing.JLabel lblIdMdl;
    private javax.swing.JLabel lblInstruct;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblModelo1;
    private javax.swing.JLabel lblModelo2;
    private javax.swing.JLabel lblMotor;
    private javax.swing.JLabel lblMotor2;
    private javax.swing.JLabel lblMotor3;
    private javax.swing.JLabel lblMotor4;
    private javax.swing.JLabel lblMotor5;
    private javax.swing.JLabel lblMotor6;
    private javax.swing.JLabel lblMotor7;
    private javax.swing.JLabel lblMotor8;
    private javax.swing.JLabel lblMotor9;
    private javax.swing.JLabel lblMotorMt;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre3;
    private javax.swing.JLabel lblNombre4;
    private javax.swing.JLabel lblNombre5;
    private javax.swing.JLabel lblNombre6;
    private javax.swing.JLabel lblNombre7;
    private javax.swing.JLabel lblNombreClr;
    private javax.swing.JLabel lblNombreEmp;
    private javax.swing.JLabel lblNombreMdl;
    private javax.swing.JTextField lblNombreMod2;
    private javax.swing.JLabel lblNumSerie;
    private javax.swing.JLabel lblNumSerie2;
    private javax.swing.JLabel lblPaisP;
    private javax.swing.JLabel lblPaisP2;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblPrecio2;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblTrans;
    private javax.swing.JLabel lblTrans2;
    private javax.swing.JLabel lblTrans3;
    private javax.swing.JLabel lblTrans4;
    private javax.swing.JLabel lblTrans5;
    private javax.swing.JLabel lblTrans6;
    private javax.swing.JLabel lblTrans7;
    private javax.swing.JLabel lblTransmision;
    private javax.swing.JLabel lblVersion;
    private javax.swing.JLabel lblVersion1;
    private javax.swing.JLabel lblVersion2;
    private javax.swing.JComboBox<String> listaEntidades;
    private javax.swing.JTextField txtApellEmp;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtColor1;
    private javax.swing.JTextField txtColor2;
    private javax.swing.JTextField txtColor3;
    private javax.swing.JTextField txtColor4;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtId1;
    private javax.swing.JTextField txtId2;
    private javax.swing.JTextField txtId3;
    private javax.swing.JTextField txtId4;
    private javax.swing.JTextField txtIdColor;
    private javax.swing.JTextField txtIdEmp;
    private javax.swing.JTextField txtIdModelo;
    private javax.swing.JTextField txtIdModelo2;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtModelo1;
    private javax.swing.JTextField txtModelo2;
    private javax.swing.JTextField txtMotor;
    private javax.swing.JTextField txtMotor2;
    private javax.swing.JTextField txtMotor3;
    private javax.swing.JTextField txtMotor4;
    private javax.swing.JTextField txtMotor5;
    private javax.swing.JTextField txtMotor6;
    private javax.swing.JTextField txtMotor7;
    private javax.swing.JTextField txtMotor8;
    private javax.swing.JTextField txtMotor9;
    private javax.swing.JTextField txtMotorMt;
    private javax.swing.JTextField txtNombreClr;
    private javax.swing.JTextField txtNombreEmp;
    private javax.swing.JTextField txtNombreMod;
    private javax.swing.JTextField txtNumSerie;
    private javax.swing.JTextField txtNumSerie2;
    private javax.swing.JTextField txtPaisP;
    private javax.swing.JTextField txtPaisP2;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtPrecio1;
    private javax.swing.JTextField txtPrecio3;
    private javax.swing.JTextField txtPrecio4;
    private javax.swing.JTextField txtPrecio5;
    private javax.swing.JTextField txtPrecio6;
    private javax.swing.JTextField txtPrecio7;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtTrans;
    private javax.swing.JTextField txtTrans2;
    private javax.swing.JTextField txtTrans3;
    private javax.swing.JTextField txtTrans4;
    private javax.swing.JTextField txtTrans5;
    private javax.swing.JTextField txtTrans6;
    private javax.swing.JTextField txtTrans7;
    private javax.swing.JTextField txtTransmision;
    private javax.swing.JTextField txtVersion;
    private javax.swing.JTextField txtVersion1;
    private javax.swing.JTextField txtVersion2;
    // End of variables declaration//GEN-END:variables
}
