/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacion.vista;

import java.awt.Color;

/**
 *
 * @author Usuario
 */
public class ModificarAdmin extends javax.swing.JPanel {

    /**
     * Creates new form ModificarAdmin
     */
    public ModificarAdmin() {
        initComponents();
        
        OcultarPanels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblAccion = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblMessage = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        listaEntidades = new javax.swing.JComboBox<>();
        ModVcls = new javax.swing.JPanel();
        lblNumSerie = new javax.swing.JLabel();
        txtNumSerie = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblPrecio = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lblPaisP = new javax.swing.JLabel();
        txtPaisP = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        lblVersion = new javax.swing.JLabel();
        txtVersion = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        lblMotor = new javax.swing.JLabel();
        txtMotor = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        lblTrans = new javax.swing.JLabel();
        txtTrans = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        lblModelo = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        lblColor = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        txtBuscar = new javax.swing.JTextField();
        jSeparator56 = new javax.swing.JSeparator();
        btnModifVcl = new javax.swing.JButton();
        lblStock = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        jSeparator68 = new javax.swing.JSeparator();
        lblNumSerie1 = new javax.swing.JLabel();
        ModVrs = new javax.swing.JPanel();
        lblIdVrs = new javax.swing.JLabel();
        txtIdVrs = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        lblNombreVrs = new javax.swing.JLabel();
        txtNombreVrs = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        lblTransVrs = new javax.swing.JLabel();
        txtTransVrs = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        lblMotorVrs = new javax.swing.JLabel();
        txtMotorVrs = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        txtBuscarVrs = new javax.swing.JTextField();
        jSeparator57 = new javax.swing.JSeparator();
        btnModifVrs = new javax.swing.JButton();
        lblIdVrs1 = new javax.swing.JLabel();
        ModModelos = new javax.swing.JPanel();
        lblIdMod = new javax.swing.JLabel();
        txtIdModelo = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        lblNombreMod = new javax.swing.JLabel();
        txtNombreMod = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        txtBuscarMod = new javax.swing.JTextField();
        jSeparator59 = new javax.swing.JSeparator();
        btnModifMod = new javax.swing.JButton();
        lblIdMod1 = new javax.swing.JLabel();
        ModColors = new javax.swing.JPanel();
        lblIdColor = new javax.swing.JLabel();
        txtIdColor = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        lblNombreColor = new javax.swing.JLabel();
        txtNombreColor = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();
        txtBuscarColor = new javax.swing.JTextField();
        jSeparator60 = new javax.swing.JSeparator();
        btnModifColor = new javax.swing.JButton();
        lblIdColor1 = new javax.swing.JLabel();
        ModEmp = new javax.swing.JPanel();
        lblIdEmp = new javax.swing.JLabel();
        txtIdEmp = new javax.swing.JTextField();
        jSeparator18 = new javax.swing.JSeparator();
        lblNombreEmp = new javax.swing.JLabel();
        txtNombreEmp = new javax.swing.JTextField();
        jSeparator19 = new javax.swing.JSeparator();
        lblApellEmp = new javax.swing.JLabel();
        txtApellEmp = new javax.swing.JTextField();
        jSeparator20 = new javax.swing.JSeparator();
        lblUsuarioEmp = new javax.swing.JLabel();
        txtUsuarioEmp = new javax.swing.JTextField();
        jSeparator21 = new javax.swing.JSeparator();
        lblContrEmp = new javax.swing.JLabel();
        txtContrEmp = new javax.swing.JTextField();
        jSeparator22 = new javax.swing.JSeparator();
        lblComsEmp = new javax.swing.JLabel();
        txtComsEmp = new javax.swing.JTextField();
        jSeparator23 = new javax.swing.JSeparator();
        lblNSSEmp = new javax.swing.JLabel();
        txtNSSEmp = new javax.swing.JTextField();
        jSeparator24 = new javax.swing.JSeparator();
        lblTelEmp = new javax.swing.JLabel();
        txtTelEmp = new javax.swing.JTextField();
        jSeparator25 = new javax.swing.JSeparator();
        lblCorreoEmp = new javax.swing.JLabel();
        txtCorreoEmp = new javax.swing.JTextField();
        jSeparator26 = new javax.swing.JSeparator();
        txtModificarEmp = new javax.swing.JTextField();
        jSeparator61 = new javax.swing.JSeparator();
        btnModifEmp = new javax.swing.JButton();
        lblIdEmp1 = new javax.swing.JLabel();
        ModDept = new javax.swing.JPanel();
        lblIdDept = new javax.swing.JLabel();
        txtIdDept = new javax.swing.JTextField();
        jSeparator27 = new javax.swing.JSeparator();
        lblNombreDept = new javax.swing.JLabel();
        txtNombreDept = new javax.swing.JTextField();
        jSeparator28 = new javax.swing.JSeparator();
        txtBuscarDept = new javax.swing.JTextField();
        jSeparator62 = new javax.swing.JSeparator();
        btnModifDpt = new javax.swing.JButton();
        lblIdDept1 = new javax.swing.JLabel();
        ModDirEmp = new javax.swing.JPanel();
        lblIdDirEmp = new javax.swing.JLabel();
        txtIdDirEmp = new javax.swing.JTextField();
        jSeparator29 = new javax.swing.JSeparator();
        lblCalle = new javax.swing.JLabel();
        txtCalle = new javax.swing.JTextField();
        jSeparator30 = new javax.swing.JSeparator();
        lblColonia = new javax.swing.JLabel();
        txtColonia = new javax.swing.JTextField();
        jSeparator31 = new javax.swing.JSeparator();
        lblNumExt = new javax.swing.JLabel();
        txtNumExt = new javax.swing.JTextField();
        jSeparator32 = new javax.swing.JSeparator();
        lblCP = new javax.swing.JLabel();
        txtCP = new javax.swing.JTextField();
        jSeparator33 = new javax.swing.JSeparator();
        txtBuscarDirEmp = new javax.swing.JTextField();
        jSeparator63 = new javax.swing.JSeparator();
        btnModifDirEmp = new javax.swing.JButton();
        lblIdDirEmp1 = new javax.swing.JLabel();
        ModCotiz = new javax.swing.JPanel();
        lblIdCot = new javax.swing.JLabel();
        txtIdCot = new javax.swing.JTextField();
        jSeparator34 = new javax.swing.JSeparator();
        lblFechCot = new javax.swing.JLabel();
        txtFechCot = new javax.swing.JTextField();
        jSeparator35 = new javax.swing.JSeparator();
        lblUsuarioCot = new javax.swing.JLabel();
        txtUsuarioCot = new javax.swing.JTextField();
        jSeparator36 = new javax.swing.JSeparator();
        lblTelCot = new javax.swing.JLabel();
        txtTelCot = new javax.swing.JTextField();
        jSeparator37 = new javax.swing.JSeparator();
        lblCorreoCot = new javax.swing.JLabel();
        txtCorreoCot = new javax.swing.JTextField();
        jSeparator38 = new javax.swing.JSeparator();
        txtBuscarCot = new javax.swing.JTextField();
        jSeparator64 = new javax.swing.JSeparator();
        btnModifCotiz = new javax.swing.JButton();
        lblIdCot1 = new javax.swing.JLabel();
        ModFacts = new javax.swing.JPanel();
        lblIdFacts = new javax.swing.JLabel();
        txtIdFacts = new javax.swing.JTextField();
        jSeparator39 = new javax.swing.JSeparator();
        lblMetPago = new javax.swing.JLabel();
        txtMetPago = new javax.swing.JTextField();
        jSeparator40 = new javax.swing.JSeparator();
        lblFechV = new javax.swing.JLabel();
        txtFechVent = new javax.swing.JTextField();
        jSeparator41 = new javax.swing.JSeparator();
        txtBuscarFact = new javax.swing.JTextField();
        jSeparator65 = new javax.swing.JSeparator();
        btnModifFacts = new javax.swing.JButton();
        lblIdDept2 = new javax.swing.JLabel();
        ModCli = new javax.swing.JPanel();
        lblIdCli = new javax.swing.JLabel();
        txtIdCli = new javax.swing.JTextField();
        jSeparator42 = new javax.swing.JSeparator();
        lblNombreCli = new javax.swing.JLabel();
        txtNombreCli = new javax.swing.JTextField();
        jSeparator43 = new javax.swing.JSeparator();
        lblApellCli = new javax.swing.JLabel();
        txtApellCli = new javax.swing.JTextField();
        jSeparator44 = new javax.swing.JSeparator();
        lblSueldoCli = new javax.swing.JLabel();
        txtSueldoCli = new javax.swing.JTextField();
        jSeparator45 = new javax.swing.JSeparator();
        lblRFCcli = new javax.swing.JLabel();
        txtRFCcli = new javax.swing.JTextField();
        jSeparator46 = new javax.swing.JSeparator();
        lblHCredCli = new javax.swing.JLabel();
        txtHCredCli = new javax.swing.JTextField();
        jSeparator47 = new javax.swing.JSeparator();
        lblFechRegCli = new javax.swing.JLabel();
        txtFechRegCli = new javax.swing.JTextField();
        jSeparator48 = new javax.swing.JSeparator();
        lblTelCli = new javax.swing.JLabel();
        txtTelCli = new javax.swing.JTextField();
        jSeparator49 = new javax.swing.JSeparator();
        lblCorreoCli = new javax.swing.JLabel();
        txtCorreoCli = new javax.swing.JTextField();
        jSeparator50 = new javax.swing.JSeparator();
        txtBuscarCli = new javax.swing.JTextField();
        jSeparator66 = new javax.swing.JSeparator();
        btnModifCli = new javax.swing.JButton();
        lblIdCli1 = new javax.swing.JLabel();
        ModDirCli = new javax.swing.JPanel();
        lblIdDirCli = new javax.swing.JLabel();
        txtIdDirCli = new javax.swing.JTextField();
        jSeparator51 = new javax.swing.JSeparator();
        lblCalleCli = new javax.swing.JLabel();
        txtCalleCli = new javax.swing.JTextField();
        jSeparator52 = new javax.swing.JSeparator();
        lblColoniaCli = new javax.swing.JLabel();
        txtColoniaCli = new javax.swing.JTextField();
        jSeparator53 = new javax.swing.JSeparator();
        lblNEDirCli = new javax.swing.JLabel();
        txtNEDirCli = new javax.swing.JTextField();
        jSeparator54 = new javax.swing.JSeparator();
        lblCPDirCli = new javax.swing.JLabel();
        txtCPDirCli = new javax.swing.JTextField();
        jSeparator55 = new javax.swing.JSeparator();
        txtBuscarDirCli = new javax.swing.JTextField();
        jSeparator67 = new javax.swing.JSeparator();
        btnModifDirCli = new javax.swing.JButton();
        lblIdDirCli1 = new javax.swing.JLabel();
        lblInstruct = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 470));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAccion.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblAccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAccion.setText("Modificar");
        jPanel1.add(lblAccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 200, -1));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 10, 470));

        lblMessage.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblMessage.setForeground(new java.awt.Color(0, 193, 75));
        jPanel1.add(lblMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 450, 20));

        lblUsuario.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuario.setText("Administrador de base de datos");
        lblUsuario.setToolTipText("");
        jPanel1.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 260, 30));

        listaEntidades.setBackground(new java.awt.Color(214, 5, 5));
        listaEntidades.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        listaEntidades.setForeground(new java.awt.Color(255, 255, 255));
        listaEntidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vehículos", "Versiones", "Modelos", "Colores", "Empleados", "Departamentos", "DireccionesEmpleados", "Cotizaciones", "Facturas", "Clientes", "DireccionesClientes" }));
        listaEntidades.setBorder(new javax.swing.border.MatteBorder(null));
        listaEntidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaEntidadesActionPerformed(evt);
            }
        });
        jPanel1.add(listaEntidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 170, 40));

        ModVcls.setBackground(new java.awt.Color(255, 255, 255));
        ModVcls.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNumSerie.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblNumSerie.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNumSerie.setText("Número de serie:");
        ModVcls.add(lblNumSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 110, 30));

        txtNumSerie.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNumSerie.setBorder(null);
        ModVcls.add(txtNumSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 240, 30));
        ModVcls.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 260, 10));

        lblPrecio.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblPrecio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPrecio.setText("Precio:");
        ModVcls.add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 100, 30));

        txtPrecio.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtPrecio.setBorder(null);
        ModVcls.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 240, 30));
        ModVcls.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 260, 10));

        lblPaisP.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblPaisP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPaisP.setText("País de procedencia:");
        ModVcls.add(lblPaisP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 120, 30));

        txtPaisP.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtPaisP.setBorder(null);
        ModVcls.add(txtPaisP, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 240, 30));
        ModVcls.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 260, 10));

        lblVersion.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblVersion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblVersion.setText("Versión:");
        ModVcls.add(lblVersion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 100, 30));

        txtVersion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtVersion.setBorder(null);
        ModVcls.add(txtVersion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 240, 30));
        ModVcls.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 260, 10));

        lblMotor.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblMotor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMotor.setText("Motor:");
        ModVcls.add(lblMotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 50, 30));

        txtMotor.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtMotor.setBorder(null);
        ModVcls.add(txtMotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 110, 30));
        ModVcls.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 130, 10));

        lblTrans.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblTrans.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTrans.setText("Transmisión:");
        ModVcls.add(lblTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 70, 30));

        txtTrans.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtTrans.setBorder(null);
        ModVcls.add(txtTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 130, 30));
        ModVcls.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 150, 10));

        lblModelo.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblModelo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblModelo.setText("Modelo:");
        ModVcls.add(lblModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 60, 30));

        txtModelo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtModelo.setBorder(null);
        ModVcls.add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 110, 30));
        ModVcls.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 130, 10));

        lblColor.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblColor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblColor.setText("Color:");
        ModVcls.add(lblColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 40, 30));

        txtColor.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtColor.setBorder(null);
        ModVcls.add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 100, 30));
        ModVcls.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 120, 10));

        txtBuscar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtBuscar.setForeground(new java.awt.Color(153, 153, 153));
        txtBuscar.setText("Introduzca algun número de serie para modificar un vehículo...");
        txtBuscar.setBorder(null);
        txtBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtBuscarMousePressed(evt);
            }
        });
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        ModVcls.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 340, 30));
        ModVcls.add(jSeparator56, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 340, 10));

        btnModifVcl.setBackground(new java.awt.Color(214, 5, 5));
        btnModifVcl.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnModifVcl.setForeground(new java.awt.Color(255, 255, 255));
        btnModifVcl.setText("Modificar");
        btnModifVcl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifVclActionPerformed(evt);
            }
        });
        ModVcls.add(btnModifVcl, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 100, 30));

        lblStock.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblStock.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStock.setText("Stock:");
        ModVcls.add(lblStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 100, 30));

        txtStock.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtStock.setBorder(null);
        ModVcls.add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 240, 30));
        ModVcls.add(jSeparator68, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 260, 10));

        lblNumSerie1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblNumSerie1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNumSerie1.setText("Número de serie:");
        ModVcls.add(lblNumSerie1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 110, 30));

        jPanel1.add(ModVcls, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 490, 320));

        ModVrs.setBackground(new java.awt.Color(255, 255, 255));
        ModVrs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIdVrs.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblIdVrs.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIdVrs.setText("Id:");
        ModVrs.add(lblIdVrs, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 110, 40));

        txtIdVrs.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtIdVrs.setBorder(null);
        ModVrs.add(txtIdVrs, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 240, 30));
        ModVrs.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 260, 10));

        lblNombreVrs.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblNombreVrs.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombreVrs.setText("Nombre:");
        ModVrs.add(lblNombreVrs, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 100, 30));

        txtNombreVrs.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNombreVrs.setBorder(null);
        ModVrs.add(txtNombreVrs, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 240, 30));
        ModVrs.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 260, 10));

        lblTransVrs.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblTransVrs.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTransVrs.setText("Transmisión:");
        ModVrs.add(lblTransVrs, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 120, 30));

        txtTransVrs.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtTransVrs.setBorder(null);
        ModVrs.add(txtTransVrs, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 240, 30));
        ModVrs.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 260, 10));

        lblMotorVrs.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblMotorVrs.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMotorVrs.setText("Motor:");
        ModVrs.add(lblMotorVrs, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 100, 30));

        txtMotorVrs.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtMotorVrs.setBorder(null);
        ModVrs.add(txtMotorVrs, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 240, 30));
        ModVrs.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 260, 10));

        txtBuscarVrs.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtBuscarVrs.setForeground(new java.awt.Color(153, 153, 153));
        txtBuscarVrs.setText("Introduzca algun Id para modificar una versión...");
        txtBuscarVrs.setBorder(null);
        txtBuscarVrs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtBuscarVrsMousePressed(evt);
            }
        });
        txtBuscarVrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarVrsActionPerformed(evt);
            }
        });
        ModVrs.add(txtBuscarVrs, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 330, 40));
        ModVrs.add(jSeparator57, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 330, 10));

        btnModifVrs.setBackground(new java.awt.Color(214, 5, 5));
        btnModifVrs.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnModifVrs.setForeground(new java.awt.Color(255, 255, 255));
        btnModifVrs.setText("Modificar");
        ModVrs.add(btnModifVrs, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 100, 30));

        lblIdVrs1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblIdVrs1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIdVrs1.setText("Id:");
        ModVrs.add(lblIdVrs1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 110, 30));

        jPanel1.add(ModVrs, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 490, 320));

        ModModelos.setBackground(new java.awt.Color(255, 255, 255));
        ModModelos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIdMod.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblIdMod.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIdMod.setText("Id:");
        ModModelos.add(lblIdMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 110, 30));

        txtIdModelo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtIdModelo.setBorder(null);
        ModModelos.add(txtIdModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 240, 30));
        ModModelos.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 260, 10));

        lblNombreMod.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblNombreMod.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombreMod.setText("Nombre:");
        ModModelos.add(lblNombreMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 100, 30));

        txtNombreMod.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNombreMod.setBorder(null);
        ModModelos.add(txtNombreMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 240, 30));
        ModModelos.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 260, 10));

        txtBuscarMod.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtBuscarMod.setForeground(new java.awt.Color(153, 153, 153));
        txtBuscarMod.setText("Introduzca algun valor para modificar un modelo...");
        txtBuscarMod.setBorder(null);
        txtBuscarMod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtBuscarModMousePressed(evt);
            }
        });
        txtBuscarMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarModActionPerformed(evt);
            }
        });
        ModModelos.add(txtBuscarMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 330, 35));
        ModModelos.add(jSeparator59, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 330, 10));

        btnModifMod.setBackground(new java.awt.Color(214, 5, 5));
        btnModifMod.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnModifMod.setForeground(new java.awt.Color(255, 255, 255));
        btnModifMod.setText("Modificar");
        ModModelos.add(btnModifMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 100, 30));

        lblIdMod1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblIdMod1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIdMod1.setText("Id:");
        ModModelos.add(lblIdMod1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 110, 40));

        jPanel1.add(ModModelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 490, 320));

        ModColors.setBackground(new java.awt.Color(255, 255, 255));
        ModColors.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIdColor.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblIdColor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIdColor.setText("Id:");
        ModColors.add(lblIdColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 110, 30));

        txtIdColor.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtIdColor.setBorder(null);
        ModColors.add(txtIdColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 240, 30));
        ModColors.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 260, 10));

        lblNombreColor.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblNombreColor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombreColor.setText("Nombre:");
        ModColors.add(lblNombreColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 100, 30));

        txtNombreColor.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNombreColor.setBorder(null);
        ModColors.add(txtNombreColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 240, 30));
        ModColors.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 260, 10));

        txtBuscarColor.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtBuscarColor.setForeground(new java.awt.Color(153, 153, 153));
        txtBuscarColor.setText("Introduzca algun Id para modificar un color...");
        txtBuscarColor.setBorder(null);
        txtBuscarColor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtBuscarColorMousePressed(evt);
            }
        });
        txtBuscarColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarColorActionPerformed(evt);
            }
        });
        ModColors.add(txtBuscarColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 330, 40));
        ModColors.add(jSeparator60, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 330, 10));

        btnModifColor.setBackground(new java.awt.Color(214, 5, 5));
        btnModifColor.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnModifColor.setForeground(new java.awt.Color(255, 255, 255));
        btnModifColor.setText("Modificar");
        ModColors.add(btnModifColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 100, 30));

        lblIdColor1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblIdColor1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIdColor1.setText("Id:");
        ModColors.add(lblIdColor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 110, 40));

        jPanel1.add(ModColors, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 490, 320));

        ModEmp.setBackground(new java.awt.Color(255, 255, 255));
        ModEmp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIdEmp.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblIdEmp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIdEmp.setText("Id del empleado:");
        ModEmp.add(lblIdEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 110, 30));

        txtIdEmp.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtIdEmp.setBorder(null);
        ModEmp.add(txtIdEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 240, 30));
        ModEmp.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 260, 10));

        lblNombreEmp.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblNombreEmp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombreEmp.setText("Nombre:");
        ModEmp.add(lblNombreEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 60, 30));

        txtNombreEmp.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNombreEmp.setBorder(null);
        ModEmp.add(txtNombreEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 130, 30));
        ModEmp.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 150, 10));

        lblApellEmp.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblApellEmp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblApellEmp.setText("Apellidos:");
        ModEmp.add(lblApellEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 60, 30));

        txtApellEmp.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtApellEmp.setBorder(null);
        ModEmp.add(txtApellEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 150, 30));
        ModEmp.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 170, 10));

        lblUsuarioEmp.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblUsuarioEmp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUsuarioEmp.setText("Usuario:");
        ModEmp.add(lblUsuarioEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 50, 30));

        txtUsuarioEmp.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtUsuarioEmp.setBorder(null);
        ModEmp.add(txtUsuarioEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 130, 30));
        ModEmp.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 150, 10));

        lblContrEmp.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblContrEmp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblContrEmp.setText("Contraseña:");
        ModEmp.add(lblContrEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 70, 30));

        txtContrEmp.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtContrEmp.setBorder(null);
        ModEmp.add(txtContrEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 150, 30));
        ModEmp.add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 170, 10));

        lblComsEmp.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblComsEmp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblComsEmp.setText("Comisión:");
        ModEmp.add(lblComsEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 100, 30));

        txtComsEmp.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtComsEmp.setBorder(null);
        ModEmp.add(txtComsEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 240, 30));
        ModEmp.add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 260, 10));

        lblNSSEmp.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblNSSEmp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNSSEmp.setText("NSS:");
        ModEmp.add(lblNSSEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 60, 30));

        txtNSSEmp.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNSSEmp.setBorder(null);
        ModEmp.add(txtNSSEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 140, 30));
        ModEmp.add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 160, 10));

        lblTelEmp.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblTelEmp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTelEmp.setText("Teléfono:");
        ModEmp.add(lblTelEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 60, 30));

        txtTelEmp.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtTelEmp.setBorder(null);
        ModEmp.add(txtTelEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 140, 30));
        ModEmp.add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 160, 10));

        lblCorreoEmp.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblCorreoEmp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCorreoEmp.setText("Correo:");
        ModEmp.add(lblCorreoEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 100, 30));

        txtCorreoEmp.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtCorreoEmp.setBorder(null);
        ModEmp.add(txtCorreoEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 220, 30));
        ModEmp.add(jSeparator26, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 240, 10));

        txtModificarEmp.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtModificarEmp.setForeground(new java.awt.Color(153, 153, 153));
        txtModificarEmp.setText("Introduzca algun valor para modificar un empleado...");
        txtModificarEmp.setBorder(null);
        txtModificarEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtModificarEmpMousePressed(evt);
            }
        });
        txtModificarEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModificarEmpActionPerformed(evt);
            }
        });
        ModEmp.add(txtModificarEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 340, 40));
        ModEmp.add(jSeparator61, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 330, 10));

        btnModifEmp.setBackground(new java.awt.Color(214, 5, 5));
        btnModifEmp.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnModifEmp.setForeground(new java.awt.Color(255, 255, 255));
        btnModifEmp.setText("Modificar");
        ModEmp.add(btnModifEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 100, 30));

        lblIdEmp1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblIdEmp1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIdEmp1.setText("Id:");
        ModEmp.add(lblIdEmp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 110, 40));

        jPanel1.add(ModEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 490, 320));

        ModDept.setBackground(new java.awt.Color(255, 255, 255));
        ModDept.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIdDept.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblIdDept.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIdDept.setText("Id del Departamento:");
        ModDept.add(lblIdDept, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 120, 30));

        txtIdDept.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtIdDept.setBorder(null);
        ModDept.add(txtIdDept, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 240, 30));
        ModDept.add(jSeparator27, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 260, 10));

        lblNombreDept.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblNombreDept.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombreDept.setText("Nombre:");
        ModDept.add(lblNombreDept, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 100, 30));

        txtNombreDept.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNombreDept.setBorder(null);
        ModDept.add(txtNombreDept, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 240, 30));
        ModDept.add(jSeparator28, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 260, 10));

        txtBuscarDept.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtBuscarDept.setForeground(new java.awt.Color(153, 153, 153));
        txtBuscarDept.setText("Introduzca algun Id para modificar un departamento...");
        txtBuscarDept.setBorder(null);
        txtBuscarDept.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtBuscarDeptMousePressed(evt);
            }
        });
        txtBuscarDept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarDeptActionPerformed(evt);
            }
        });
        ModDept.add(txtBuscarDept, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 360, 40));
        ModDept.add(jSeparator62, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 360, 10));

        btnModifDpt.setBackground(new java.awt.Color(214, 5, 5));
        btnModifDpt.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnModifDpt.setForeground(new java.awt.Color(255, 255, 255));
        btnModifDpt.setText("Modificar");
        ModDept.add(btnModifDpt, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 100, 30));

        lblIdDept1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblIdDept1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIdDept1.setText("Id:");
        ModDept.add(lblIdDept1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 110, 40));

        jPanel1.add(ModDept, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 490, 320));

        ModDirEmp.setBackground(new java.awt.Color(255, 255, 255));
        ModDirEmp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIdDirEmp.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblIdDirEmp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIdDirEmp.setText("Id:");
        ModDirEmp.add(lblIdDirEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 110, 30));

        txtIdDirEmp.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtIdDirEmp.setBorder(null);
        ModDirEmp.add(txtIdDirEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 240, 30));
        ModDirEmp.add(jSeparator29, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 260, 10));

        lblCalle.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblCalle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCalle.setText("Calle:");
        ModDirEmp.add(lblCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 70, 30));

        txtCalle.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtCalle.setBorder(null);
        ModDirEmp.add(txtCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 240, 30));
        ModDirEmp.add(jSeparator30, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 260, 10));

        lblColonia.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblColonia.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblColonia.setText("Colonia:");
        ModDirEmp.add(lblColonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 80, 30));

        txtColonia.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtColonia.setBorder(null);
        ModDirEmp.add(txtColonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 240, 30));
        ModDirEmp.add(jSeparator31, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 260, 10));

        lblNumExt.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblNumExt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNumExt.setText("Número Exterior:");
        ModDirEmp.add(lblNumExt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 110, 30));

        txtNumExt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNumExt.setBorder(null);
        ModDirEmp.add(txtNumExt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 240, 30));
        ModDirEmp.add(jSeparator32, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 260, 10));

        lblCP.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblCP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCP.setText("Código Postal:");
        ModDirEmp.add(lblCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 110, 30));

        txtCP.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtCP.setBorder(null);
        ModDirEmp.add(txtCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 240, 30));
        ModDirEmp.add(jSeparator33, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 260, 10));

        txtBuscarDirEmp.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtBuscarDirEmp.setForeground(new java.awt.Color(153, 153, 153));
        txtBuscarDirEmp.setText("Introduzca algun valor para modificar una dirección...");
        txtBuscarDirEmp.setBorder(null);
        txtBuscarDirEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtBuscarDirEmpMousePressed(evt);
            }
        });
        txtBuscarDirEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarDirEmpActionPerformed(evt);
            }
        });
        ModDirEmp.add(txtBuscarDirEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 360, 40));
        ModDirEmp.add(jSeparator63, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 350, 10));

        btnModifDirEmp.setBackground(new java.awt.Color(214, 5, 5));
        btnModifDirEmp.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnModifDirEmp.setForeground(new java.awt.Color(255, 255, 255));
        btnModifDirEmp.setText("Modificar");
        btnModifDirEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifDirEmpActionPerformed(evt);
            }
        });
        ModDirEmp.add(btnModifDirEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 100, 30));

        lblIdDirEmp1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblIdDirEmp1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIdDirEmp1.setText("Id:");
        ModDirEmp.add(lblIdDirEmp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 110, 40));

        jPanel1.add(ModDirEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 490, 320));

        ModCotiz.setBackground(new java.awt.Color(255, 255, 255));
        ModCotiz.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIdCot.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblIdCot.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIdCot.setText("Id de la Cotización:");
        ModCotiz.add(lblIdCot, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 120, 30));

        txtIdCot.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtIdCot.setBorder(null);
        ModCotiz.add(txtIdCot, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 240, 30));
        ModCotiz.add(jSeparator34, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 260, 10));

        lblFechCot.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblFechCot.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFechCot.setText("Fecha de cotización:");
        ModCotiz.add(lblFechCot, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 120, 30));

        txtFechCot.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtFechCot.setBorder(null);
        ModCotiz.add(txtFechCot, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 240, 30));
        ModCotiz.add(jSeparator35, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 260, 10));

        lblUsuarioCot.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblUsuarioCot.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUsuarioCot.setText("Nombre del Usuario:");
        ModCotiz.add(lblUsuarioCot, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 120, 30));

        txtUsuarioCot.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtUsuarioCot.setBorder(null);
        ModCotiz.add(txtUsuarioCot, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 240, 30));
        ModCotiz.add(jSeparator36, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 260, 10));

        lblTelCot.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblTelCot.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTelCot.setText("Teléfono:");
        ModCotiz.add(lblTelCot, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 110, 30));

        txtTelCot.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtTelCot.setBorder(null);
        ModCotiz.add(txtTelCot, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 240, 30));
        ModCotiz.add(jSeparator37, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 260, 10));

        lblCorreoCot.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblCorreoCot.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCorreoCot.setText("Correo:");
        ModCotiz.add(lblCorreoCot, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 110, 30));

        txtCorreoCot.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtCorreoCot.setBorder(null);
        ModCotiz.add(txtCorreoCot, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 240, 30));
        ModCotiz.add(jSeparator38, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 260, 10));

        txtBuscarCot.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtBuscarCot.setForeground(new java.awt.Color(153, 153, 153));
        txtBuscarCot.setText("Introduzca algun valor para modificar una cotización...");
        txtBuscarCot.setBorder(null);
        txtBuscarCot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtBuscarCotMousePressed(evt);
            }
        });
        txtBuscarCot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarCotActionPerformed(evt);
            }
        });
        ModCotiz.add(txtBuscarCot, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 360, 40));
        ModCotiz.add(jSeparator64, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 350, 10));

        btnModifCotiz.setBackground(new java.awt.Color(214, 5, 5));
        btnModifCotiz.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnModifCotiz.setForeground(new java.awt.Color(255, 255, 255));
        btnModifCotiz.setText("Modificar");
        ModCotiz.add(btnModifCotiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 100, 30));

        lblIdCot1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblIdCot1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIdCot1.setText("Id:");
        ModCotiz.add(lblIdCot1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 110, 40));

        jPanel1.add(ModCotiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 490, 320));

        ModFacts.setBackground(new java.awt.Color(255, 255, 255));
        ModFacts.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIdFacts.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblIdFacts.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIdFacts.setText("Código de la factura:");
        ModFacts.add(lblIdFacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 120, 30));

        txtIdFacts.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtIdFacts.setBorder(null);
        ModFacts.add(txtIdFacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 240, 30));
        ModFacts.add(jSeparator39, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 260, 10));

        lblMetPago.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblMetPago.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMetPago.setText("Método de pago:");
        ModFacts.add(lblMetPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 120, 30));

        txtMetPago.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtMetPago.setBorder(null);
        ModFacts.add(txtMetPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 240, 30));
        ModFacts.add(jSeparator40, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 260, 10));

        lblFechV.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblFechV.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFechV.setText("Fecha de venta:");
        ModFacts.add(lblFechV, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 120, 30));

        txtFechVent.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtFechVent.setBorder(null);
        ModFacts.add(txtFechVent, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 240, 30));
        ModFacts.add(jSeparator41, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 260, 10));

        txtBuscarFact.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtBuscarFact.setForeground(new java.awt.Color(153, 153, 153));
        txtBuscarFact.setText("Introduzca algun Código para modificar una factura...");
        txtBuscarFact.setBorder(null);
        txtBuscarFact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtBuscarFactMousePressed(evt);
            }
        });
        txtBuscarFact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarFactActionPerformed(evt);
            }
        });
        ModFacts.add(txtBuscarFact, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 360, 40));
        ModFacts.add(jSeparator65, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 350, 10));

        btnModifFacts.setBackground(new java.awt.Color(214, 5, 5));
        btnModifFacts.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnModifFacts.setForeground(new java.awt.Color(255, 255, 255));
        btnModifFacts.setText("Modificar");
        ModFacts.add(btnModifFacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 100, 30));

        lblIdDept2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblIdDept2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIdDept2.setText("Código:");
        ModFacts.add(lblIdDept2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 110, 40));

        jPanel1.add(ModFacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 490, 320));

        ModCli.setBackground(new java.awt.Color(255, 255, 255));
        ModCli.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIdCli.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblIdCli.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIdCli.setText("Id del cliente:");
        ModCli.add(lblIdCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 110, 30));

        txtIdCli.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtIdCli.setBorder(null);
        ModCli.add(txtIdCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 240, 30));
        ModCli.add(jSeparator42, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 260, 10));

        lblNombreCli.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblNombreCli.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombreCli.setText("Nombre:");
        ModCli.add(lblNombreCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 50, 30));

        txtNombreCli.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNombreCli.setBorder(null);
        ModCli.add(txtNombreCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 140, 30));
        ModCli.add(jSeparator43, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 160, 10));

        lblApellCli.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblApellCli.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblApellCli.setText("Apellidos:");
        ModCli.add(lblApellCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 60, 30));

        txtApellCli.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtApellCli.setBorder(null);
        ModCli.add(txtApellCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 150, 30));
        ModCli.add(jSeparator44, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 170, 10));

        lblSueldoCli.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblSueldoCli.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSueldoCli.setText("Sueldo:");
        ModCli.add(lblSueldoCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 50, 30));

        txtSueldoCli.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtSueldoCli.setBorder(null);
        ModCli.add(txtSueldoCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 140, 30));
        ModCli.add(jSeparator45, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 160, 10));

        lblRFCcli.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblRFCcli.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRFCcli.setText("RFC:");
        ModCli.add(lblRFCcli, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 30, 30));

        txtRFCcli.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtRFCcli.setBorder(null);
        ModCli.add(txtRFCcli, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 150, 30));
        ModCli.add(jSeparator46, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 170, 10));

        lblHCredCli.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblHCredCli.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHCredCli.setText("Historial Crediticio:");
        ModCli.add(lblHCredCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 110, 30));

        txtHCredCli.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtHCredCli.setBorder(null);
        ModCli.add(txtHCredCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 240, 30));
        ModCli.add(jSeparator47, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 260, 10));

        lblFechRegCli.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblFechRegCli.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFechRegCli.setText("Fecha de registro:");
        ModCli.add(lblFechRegCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 100, 30));

        txtFechRegCli.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtFechRegCli.setBorder(null);
        ModCli.add(txtFechRegCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 120, 30));
        ModCli.add(jSeparator48, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 140, 10));

        lblTelCli.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblTelCli.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTelCli.setText("Teléfono:");
        ModCli.add(lblTelCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 60, 30));

        txtTelCli.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtTelCli.setBorder(null);
        ModCli.add(txtTelCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 140, 30));
        ModCli.add(jSeparator49, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 160, 10));

        lblCorreoCli.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblCorreoCli.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCorreoCli.setText("Correo:");
        ModCli.add(lblCorreoCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 100, 30));

        txtCorreoCli.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtCorreoCli.setBorder(null);
        ModCli.add(txtCorreoCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 220, 30));
        ModCli.add(jSeparator50, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 240, 10));

        txtBuscarCli.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtBuscarCli.setForeground(new java.awt.Color(153, 153, 153));
        txtBuscarCli.setText("Introduzca algun valor para modificar un cliente...");
        txtBuscarCli.setBorder(null);
        txtBuscarCli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtBuscarCliMousePressed(evt);
            }
        });
        txtBuscarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarCliActionPerformed(evt);
            }
        });
        ModCli.add(txtBuscarCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 360, 40));
        ModCli.add(jSeparator66, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 350, 10));

        btnModifCli.setBackground(new java.awt.Color(214, 5, 5));
        btnModifCli.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnModifCli.setForeground(new java.awt.Color(255, 255, 255));
        btnModifCli.setText("Modificar");
        ModCli.add(btnModifCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 100, 30));

        lblIdCli1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblIdCli1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIdCli1.setText("Id:");
        ModCli.add(lblIdCli1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 110, 40));

        jPanel1.add(ModCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 490, 320));

        ModDirCli.setBackground(new java.awt.Color(255, 255, 255));
        ModDirCli.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIdDirCli.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblIdDirCli.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIdDirCli.setText("Id:");
        ModDirCli.add(lblIdDirCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 110, 30));

        txtIdDirCli.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtIdDirCli.setBorder(null);
        ModDirCli.add(txtIdDirCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 240, 30));
        ModDirCli.add(jSeparator51, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 260, 10));

        lblCalleCli.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblCalleCli.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCalleCli.setText("Calle:");
        ModDirCli.add(lblCalleCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 70, 30));

        txtCalleCli.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtCalleCli.setBorder(null);
        ModDirCli.add(txtCalleCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 240, 30));
        ModDirCli.add(jSeparator52, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 260, 10));

        lblColoniaCli.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblColoniaCli.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblColoniaCli.setText("Colonia:");
        ModDirCli.add(lblColoniaCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 80, 30));

        txtColoniaCli.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtColoniaCli.setBorder(null);
        ModDirCli.add(txtColoniaCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 240, 30));
        ModDirCli.add(jSeparator53, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 260, 10));

        lblNEDirCli.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblNEDirCli.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNEDirCli.setText("Número Exterior:");
        ModDirCli.add(lblNEDirCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 110, 30));

        txtNEDirCli.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNEDirCli.setBorder(null);
        ModDirCli.add(txtNEDirCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 240, 30));
        ModDirCli.add(jSeparator54, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 260, 10));

        lblCPDirCli.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblCPDirCli.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCPDirCli.setText("Código Postal:");
        ModDirCli.add(lblCPDirCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 110, 30));

        txtCPDirCli.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtCPDirCli.setBorder(null);
        ModDirCli.add(txtCPDirCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 240, 30));
        ModDirCli.add(jSeparator55, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 260, 10));

        txtBuscarDirCli.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtBuscarDirCli.setForeground(new java.awt.Color(153, 153, 153));
        txtBuscarDirCli.setText("Introduzca algun valor para modificar un dirección...");
        txtBuscarDirCli.setBorder(null);
        txtBuscarDirCli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtBuscarDirCliMousePressed(evt);
            }
        });
        txtBuscarDirCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarDirCliActionPerformed(evt);
            }
        });
        ModDirCli.add(txtBuscarDirCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 360, 40));
        ModDirCli.add(jSeparator67, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 350, 10));

        btnModifDirCli.setBackground(new java.awt.Color(214, 5, 5));
        btnModifDirCli.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnModifDirCli.setForeground(new java.awt.Color(255, 255, 255));
        btnModifDirCli.setText("Modificar");
        ModDirCli.add(btnModifDirCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 100, 30));

        lblIdDirCli1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblIdDirCli1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIdDirCli1.setText("Id:");
        ModDirCli.add(lblIdDirCli1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 110, 40));

        jPanel1.add(ModDirCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 490, 320));

        lblInstruct.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblInstruct.setForeground(new java.awt.Color(153, 153, 153));
        lblInstruct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstruct.setText("Seleccione una entidad para modificar información:");
        jPanel1.add(lblInstruct, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 320, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void listaEntidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaEntidadesActionPerformed
        switch (listaEntidades.getSelectedItem().toString()) {
            case "Vehículos":
            OcultarPanels();
            ModVcls.setVisible(true);
            break;
            case "Versiones":
            OcultarPanels();
            ModVrs.setVisible(true);
            break;
            case "Modelos":
            OcultarPanels();
            ModModelos.setVisible(true);
            break;
            case "Colores":
            OcultarPanels();
            ModColors.setVisible(true);
            break;
            case "Empleados":
            OcultarPanels();
            ModEmp.setVisible(true);
            break;
            case "Departamentos":
            OcultarPanels();
            ModDept.setVisible(true);
            break;
            case "DireccionesEmpleados":
            OcultarPanels();
            ModDirEmp.setVisible(true);
            break;
            case "Cotizaciones":
            OcultarPanels();
            ModCotiz.setVisible(true);
            break;
            case "Facturas":
            OcultarPanels();
            ModFacts.setVisible(true);
            break;
            case "Clientes":
            OcultarPanels();
            ModCli.setVisible(true);
            break;
            case "DireccionesClientes":
            OcultarPanels();
            ModDirCli.setVisible(true);
            break;
            default:
            break;
        }
    }//GEN-LAST:event_listaEntidadesActionPerformed

    private void txtBuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarMousePressed
        if (txtBuscar.getText().equals("Introduzca algun número de serie para modificar un vehículo...")) {
            txtBuscar.setText("");
            txtBuscar.setForeground(Color.black);
        }else if(txtBuscar.getText().isEmpty()) {
            txtBuscar.setText("Introduzca algun número de serie para modificar un vehículo...");
            txtBuscar.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtBuscarMousePressed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed

    }//GEN-LAST:event_txtBuscarActionPerformed

    private void txtBuscarVrsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarVrsMousePressed
        if (txtBuscarVrs.getText().equals("Introduzca algun Id para modificar una versión...")) {
            txtBuscarVrs.setText("");
            txtBuscarVrs.setForeground(Color.black);
        }else if(txtBuscarVrs.getText().isEmpty()) {
            txtBuscarVrs.setText("Introduzca algun Id para modificar una versión...");
            txtBuscarVrs.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtBuscarVrsMousePressed

    private void txtBuscarVrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarVrsActionPerformed

    }//GEN-LAST:event_txtBuscarVrsActionPerformed

    private void txtBuscarModMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarModMousePressed
        if (txtBuscarMod.getText().equals("Introduzca algun Id para modificar un modelo...")) {
            txtBuscarMod.setText("");
            txtBuscarMod.setForeground(Color.black);
        }else if(txtBuscarMod.getText().isEmpty()) {
            txtBuscarMod.setText("Introduzca algun Id para modificar un modelo...");
            txtBuscarMod.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtBuscarModMousePressed

    private void txtBuscarModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarModActionPerformed

    }//GEN-LAST:event_txtBuscarModActionPerformed

    private void txtBuscarColorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarColorMousePressed
        if (txtBuscarColor.getText().equals("Introduzca algun Id para modificar un color...")) {
            txtBuscarColor.setText("");
            txtBuscarColor.setForeground(Color.black);
        }else if(txtBuscarColor.getText().isEmpty()) {
            txtBuscarColor.setText("Introduzca algun Id para modificar un color...");
            txtBuscarColor.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtBuscarColorMousePressed

    private void txtBuscarColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarColorActionPerformed

    }//GEN-LAST:event_txtBuscarColorActionPerformed

    private void txtModificarEmpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtModificarEmpMousePressed
        if (txtModificarEmp.getText().equals("Introduzca algun Id para modificar un empleado...")) {
            txtModificarEmp.setText("");
            txtModificarEmp.setForeground(Color.black);
        }else if(txtModificarEmp.getText().isEmpty()) {
            txtModificarEmp.setText("Introduzca algun Id para modificar un empleado...");
            txtModificarEmp.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtModificarEmpMousePressed

    private void txtModificarEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModificarEmpActionPerformed

    }//GEN-LAST:event_txtModificarEmpActionPerformed

    private void txtBuscarDeptMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarDeptMousePressed
        if (txtBuscarDept.getText().equals("Introduzca algun Id para modificar un departamento...")) {
            txtBuscarDept.setText("");
            txtBuscarDept.setForeground(Color.black);
        }else if(txtBuscarDept.getText().isEmpty()) {
            txtBuscarDept.setText("Introduzca algun Id para modificar un departamento...");
            txtBuscarDept.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtBuscarDeptMousePressed

    private void txtBuscarDeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarDeptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarDeptActionPerformed

    private void txtBuscarDirEmpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarDirEmpMousePressed
        if (txtBuscarDirEmp.getText().equals("Introduzca algun Id para modificar una dirección...")) {
            txtBuscarDirEmp.setText("");
            txtBuscarDirEmp.setForeground(Color.black);
        }else if(txtBuscarDirEmp.getText().isEmpty()) {
            txtBuscarDirEmp.setText("Introduzca algun Id para modificar una dirección...");
            txtBuscarDirEmp.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtBuscarDirEmpMousePressed

    private void txtBuscarDirEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarDirEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarDirEmpActionPerformed

    private void txtBuscarCotMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarCotMousePressed
        if (txtBuscarCot.getText().equals("Introduzca algun Id para modificar una cotización...")) {
            txtBuscarCot.setText("");
            txtBuscarCot.setForeground(Color.black);
        }else if(txtBuscarCot.getText().isEmpty()) {
            txtBuscarCot.setText("Introduzca algun Id para modificar una cotización...");
            txtBuscarCot.setForeground(Color.gray);
        }       
    }//GEN-LAST:event_txtBuscarCotMousePressed

    private void txtBuscarCotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarCotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarCotActionPerformed

    private void txtBuscarFactMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarFactMousePressed
        if (txtBuscarFact.getText().equals("Introduzca algun Código para modificar una factura...")) {
            txtBuscarFact.setText("");
            txtBuscarFact.setForeground(Color.black);
        }else if(txtBuscarFact.getText().isEmpty()) {
            txtBuscarFact.setText("Introduzca algun Código para modificar una factura...");
            txtBuscarFact.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtBuscarFactMousePressed

    private void txtBuscarFactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarFactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarFactActionPerformed

    private void txtBuscarCliMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarCliMousePressed
        if (txtBuscarCli.getText().equals("Introduzca algun Id para modificar un cliente...")) {
            txtBuscarCli.setText("");
            txtBuscarCli.setForeground(Color.black);
        }else if(txtBuscarCli.getText().isEmpty()) {
            txtBuscarCli.setText("Introduzca algun Id para modificar un cliente...");
            txtBuscarCli.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtBuscarCliMousePressed

    private void txtBuscarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarCliActionPerformed

    private void txtBuscarDirCliMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarDirCliMousePressed
        if (txtBuscarDirCli.getText().equals("Introduzca algun Id para modificar una dirección...")) {
            txtBuscarDirCli.setText("");
            txtBuscarDirCli.setForeground(Color.black);
        }else if(txtBuscarDirCli.getText().isEmpty()) {
            txtBuscarDirCli.setText("Introduzca algun Id para modificar una dirección...");
            txtBuscarDirCli.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtBuscarDirCliMousePressed

    private void txtBuscarDirCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarDirCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarDirCliActionPerformed

    private void btnModifVclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifVclActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModifVclActionPerformed

    private void btnModifDirEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifDirEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModifDirEmpActionPerformed

    private void OcultarPanels() {
        ModVcls.setVisible(false);
        ModVrs.setVisible(false);
        ModModelos.setVisible(false);
        ModColors.setVisible(false);
        ModEmp.setVisible(false);
        ModDept.setVisible(false);
        ModDirEmp.setVisible(false);
        ModCotiz.setVisible(false);
        ModFacts.setVisible(false);
        ModCli.setVisible(false);
        ModDirCli.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ModCli;
    private javax.swing.JPanel ModColors;
    private javax.swing.JPanel ModCotiz;
    public javax.swing.JPanel ModDept;
    private javax.swing.JPanel ModDirCli;
    public javax.swing.JPanel ModDirEmp;
    private javax.swing.JPanel ModEmp;
    private javax.swing.JPanel ModFacts;
    private javax.swing.JPanel ModModelos;
    private javax.swing.JPanel ModVcls;
    private javax.swing.JPanel ModVrs;
    private javax.swing.JButton btnModifCli;
    private javax.swing.JButton btnModifColor;
    private javax.swing.JButton btnModifCotiz;
    private javax.swing.JButton btnModifDirCli;
    private javax.swing.JButton btnModifDirEmp;
    private javax.swing.JButton btnModifDpt;
    private javax.swing.JButton btnModifEmp;
    private javax.swing.JButton btnModifFacts;
    private javax.swing.JButton btnModifMod;
    private javax.swing.JButton btnModifVcl;
    private javax.swing.JButton btnModifVrs;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator28;
    private javax.swing.JSeparator jSeparator29;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator30;
    private javax.swing.JSeparator jSeparator31;
    private javax.swing.JSeparator jSeparator32;
    private javax.swing.JSeparator jSeparator33;
    private javax.swing.JSeparator jSeparator34;
    private javax.swing.JSeparator jSeparator35;
    private javax.swing.JSeparator jSeparator36;
    private javax.swing.JSeparator jSeparator37;
    private javax.swing.JSeparator jSeparator38;
    private javax.swing.JSeparator jSeparator39;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator40;
    private javax.swing.JSeparator jSeparator41;
    private javax.swing.JSeparator jSeparator42;
    private javax.swing.JSeparator jSeparator43;
    private javax.swing.JSeparator jSeparator44;
    private javax.swing.JSeparator jSeparator45;
    private javax.swing.JSeparator jSeparator46;
    private javax.swing.JSeparator jSeparator47;
    private javax.swing.JSeparator jSeparator48;
    private javax.swing.JSeparator jSeparator49;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator50;
    private javax.swing.JSeparator jSeparator51;
    private javax.swing.JSeparator jSeparator52;
    private javax.swing.JSeparator jSeparator53;
    private javax.swing.JSeparator jSeparator54;
    private javax.swing.JSeparator jSeparator55;
    private javax.swing.JSeparator jSeparator56;
    private javax.swing.JSeparator jSeparator57;
    private javax.swing.JSeparator jSeparator59;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator60;
    private javax.swing.JSeparator jSeparator61;
    private javax.swing.JSeparator jSeparator62;
    private javax.swing.JSeparator jSeparator63;
    private javax.swing.JSeparator jSeparator64;
    private javax.swing.JSeparator jSeparator65;
    private javax.swing.JSeparator jSeparator66;
    private javax.swing.JSeparator jSeparator67;
    private javax.swing.JSeparator jSeparator68;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblAccion;
    private javax.swing.JLabel lblApellCli;
    private javax.swing.JLabel lblApellEmp;
    private javax.swing.JLabel lblCP;
    private javax.swing.JLabel lblCPDirCli;
    private javax.swing.JLabel lblCalle;
    private javax.swing.JLabel lblCalleCli;
    private javax.swing.JLabel lblColonia;
    private javax.swing.JLabel lblColoniaCli;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblComsEmp;
    private javax.swing.JLabel lblContrEmp;
    private javax.swing.JLabel lblCorreoCli;
    private javax.swing.JLabel lblCorreoCot;
    private javax.swing.JLabel lblCorreoEmp;
    private javax.swing.JLabel lblFechCot;
    private javax.swing.JLabel lblFechRegCli;
    private javax.swing.JLabel lblFechV;
    private javax.swing.JLabel lblHCredCli;
    private javax.swing.JLabel lblIdCli;
    private javax.swing.JLabel lblIdCli1;
    private javax.swing.JLabel lblIdColor;
    private javax.swing.JLabel lblIdColor1;
    private javax.swing.JLabel lblIdCot;
    private javax.swing.JLabel lblIdCot1;
    private javax.swing.JLabel lblIdDept;
    private javax.swing.JLabel lblIdDept1;
    private javax.swing.JLabel lblIdDept2;
    private javax.swing.JLabel lblIdDirCli;
    private javax.swing.JLabel lblIdDirCli1;
    private javax.swing.JLabel lblIdDirEmp;
    private javax.swing.JLabel lblIdDirEmp1;
    private javax.swing.JLabel lblIdEmp;
    private javax.swing.JLabel lblIdEmp1;
    private javax.swing.JLabel lblIdFacts;
    private javax.swing.JLabel lblIdMod;
    private javax.swing.JLabel lblIdMod1;
    private javax.swing.JLabel lblIdVrs;
    private javax.swing.JLabel lblIdVrs1;
    private javax.swing.JLabel lblInstruct;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblMetPago;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblMotor;
    private javax.swing.JLabel lblMotorVrs;
    private javax.swing.JLabel lblNEDirCli;
    private javax.swing.JLabel lblNSSEmp;
    private javax.swing.JLabel lblNombreCli;
    private javax.swing.JLabel lblNombreColor;
    private javax.swing.JLabel lblNombreDept;
    private javax.swing.JLabel lblNombreEmp;
    private javax.swing.JLabel lblNombreMod;
    private javax.swing.JLabel lblNombreVrs;
    private javax.swing.JLabel lblNumExt;
    private javax.swing.JLabel lblNumSerie;
    private javax.swing.JLabel lblNumSerie1;
    private javax.swing.JLabel lblPaisP;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblRFCcli;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblSueldoCli;
    private javax.swing.JLabel lblTelCli;
    private javax.swing.JLabel lblTelCot;
    private javax.swing.JLabel lblTelEmp;
    private javax.swing.JLabel lblTrans;
    private javax.swing.JLabel lblTransVrs;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuarioCot;
    private javax.swing.JLabel lblUsuarioEmp;
    private javax.swing.JLabel lblVersion;
    private javax.swing.JComboBox<String> listaEntidades;
    private javax.swing.JTextField txtApellCli;
    private javax.swing.JTextField txtApellEmp;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtBuscarCli;
    private javax.swing.JTextField txtBuscarColor;
    private javax.swing.JTextField txtBuscarCot;
    private javax.swing.JTextField txtBuscarDept;
    private javax.swing.JTextField txtBuscarDirCli;
    private javax.swing.JTextField txtBuscarDirEmp;
    private javax.swing.JTextField txtBuscarFact;
    private javax.swing.JTextField txtBuscarMod;
    private javax.swing.JTextField txtBuscarVrs;
    private javax.swing.JTextField txtCP;
    private javax.swing.JTextField txtCPDirCli;
    private javax.swing.JTextField txtCalle;
    private javax.swing.JTextField txtCalleCli;
    private javax.swing.JTextField txtColonia;
    private javax.swing.JTextField txtColoniaCli;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtComsEmp;
    private javax.swing.JTextField txtContrEmp;
    private javax.swing.JTextField txtCorreoCli;
    private javax.swing.JTextField txtCorreoCot;
    private javax.swing.JTextField txtCorreoEmp;
    private javax.swing.JTextField txtFechCot;
    private javax.swing.JTextField txtFechRegCli;
    private javax.swing.JTextField txtFechVent;
    private javax.swing.JTextField txtHCredCli;
    private javax.swing.JTextField txtIdCli;
    private javax.swing.JTextField txtIdColor;
    private javax.swing.JTextField txtIdCot;
    private javax.swing.JTextField txtIdDept;
    private javax.swing.JTextField txtIdDirCli;
    private javax.swing.JTextField txtIdDirEmp;
    private javax.swing.JTextField txtIdEmp;
    private javax.swing.JTextField txtIdFacts;
    private javax.swing.JTextField txtIdModelo;
    private javax.swing.JTextField txtIdVrs;
    private javax.swing.JTextField txtMetPago;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtModificarEmp;
    private javax.swing.JTextField txtMotor;
    private javax.swing.JTextField txtMotorVrs;
    private javax.swing.JTextField txtNEDirCli;
    private javax.swing.JTextField txtNSSEmp;
    private javax.swing.JTextField txtNombreCli;
    private javax.swing.JTextField txtNombreColor;
    private javax.swing.JTextField txtNombreDept;
    private javax.swing.JTextField txtNombreEmp;
    private javax.swing.JTextField txtNombreMod;
    private javax.swing.JTextField txtNombreVrs;
    private javax.swing.JTextField txtNumExt;
    private javax.swing.JTextField txtNumSerie;
    private javax.swing.JTextField txtPaisP;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtRFCcli;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtSueldoCli;
    private javax.swing.JTextField txtTelCli;
    private javax.swing.JTextField txtTelCot;
    private javax.swing.JTextField txtTelEmp;
    private javax.swing.JTextField txtTrans;
    private javax.swing.JTextField txtTransVrs;
    private javax.swing.JTextField txtUsuarioCot;
    private javax.swing.JTextField txtUsuarioEmp;
    private javax.swing.JTextField txtVersion;
    // End of variables declaration//GEN-END:variables
}
