/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacion.vista;

import java.awt.Color;

/**
 *
 * @author zamud
 */
public class Page9ModifFact extends javax.swing.JPanel {

    /**
     * Creates new form Page9ModifFact
     */
    public Page9ModifFact() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        lblAccion = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblMessage = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        ModFacts = new javax.swing.JPanel();
        lblIdFacts = new javax.swing.JLabel();
        txtIdFacts = new javax.swing.JTextField();
        jSeparator39 = new javax.swing.JSeparator();
        lblMetPago = new javax.swing.JLabel();
        txtMetPago = new javax.swing.JTextField();
        jSeparator40 = new javax.swing.JSeparator();
        lblFechV = new javax.swing.JLabel();
        txtFechVent = new javax.swing.JTextField();
        jSeparator41 = new javax.swing.JSeparator();
        txtBuscar = new javax.swing.JTextField();
        jSeparator65 = new javax.swing.JSeparator();
        btnModifFacts = new javax.swing.JButton();
        lblIdVrs = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(600, 470));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsuario.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuario.setText("Vendedor de piso");
        lblUsuario.setToolTipText("");
        jPanel4.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 220, 50));

        lblAccion.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblAccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAccion.setText("Modificar Factura");
        jPanel4.add(lblAccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 190, -1));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 10, 470));

        lblMessage.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblMessage.setForeground(new java.awt.Color(0, 193, 75));
        jPanel4.add(lblMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 450, 30));

        ModFacts.setBackground(new java.awt.Color(255, 255, 255));
        ModFacts.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIdFacts.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblIdFacts.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIdFacts.setText("Código de la factura:");
        ModFacts.add(lblIdFacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 120, 30));

        txtIdFacts.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtIdFacts.setBorder(null);
        ModFacts.add(txtIdFacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 240, 30));
        ModFacts.add(jSeparator39, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 260, 10));

        lblMetPago.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblMetPago.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMetPago.setText("Método de pago:");
        ModFacts.add(lblMetPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 120, 30));

        txtMetPago.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtMetPago.setBorder(null);
        ModFacts.add(txtMetPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 240, 30));
        ModFacts.add(jSeparator40, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 260, 10));

        lblFechV.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblFechV.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFechV.setText("Fecha de venta:");
        ModFacts.add(lblFechV, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 120, 30));

        txtFechVent.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtFechVent.setBorder(null);
        ModFacts.add(txtFechVent, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 240, 30));
        ModFacts.add(jSeparator41, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 260, 10));

        txtBuscar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtBuscar.setForeground(new java.awt.Color(153, 153, 153));
        txtBuscar.setText("Introduzca algun Código para modificar una factura...");
        txtBuscar.setBorder(null);
        txtBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtBuscarMousePressed(evt);
            }
        });
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        ModFacts.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 360, 40));
        ModFacts.add(jSeparator65, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 350, 10));

        btnModifFacts.setBackground(new java.awt.Color(214, 5, 5));
        btnModifFacts.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnModifFacts.setForeground(new java.awt.Color(255, 255, 255));
        btnModifFacts.setText("Modificar");
        ModFacts.add(btnModifFacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 100, 30));

        lblIdVrs.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblIdVrs.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIdVrs.setText("Código:");
        ModFacts.add(lblIdVrs, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 90, 40));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(ModFacts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(ModFacts, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 490, 310));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 270, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 270, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 240, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 240, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarMousePressed
        if (txtBuscar.getText().equals("Introduzca algun Código para modificar una factura...")) {
            txtBuscar.setText("");
            txtBuscar.setForeground(Color.black);
        }else if(txtBuscar.getText().isEmpty()) {
            txtBuscar.setText("Introduzca algun Código para modificar una factura...");
            txtBuscar.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtBuscarMousePressed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ModFacts;
    private javax.swing.JButton btnModifFacts;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator39;
    private javax.swing.JSeparator jSeparator40;
    private javax.swing.JSeparator jSeparator41;
    private javax.swing.JSeparator jSeparator65;
    private javax.swing.JLabel lblAccion;
    private javax.swing.JLabel lblFechV;
    private javax.swing.JLabel lblIdFacts;
    private javax.swing.JLabel lblIdVrs;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblMetPago;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtFechVent;
    private javax.swing.JTextField txtIdFacts;
    private javax.swing.JTextField txtMetPago;
    // End of variables declaration//GEN-END:variables
}
