/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacion.vista;

import java.awt.Color;

/**
 *
 * @author zamud
 */
public class Page5ModifCli extends javax.swing.JPanel {

    /**
     * Creates new form Page5ModifCli
     */
    public Page5ModifCli() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblAccion = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblMessage = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNomCli = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblApellidos = new javax.swing.JLabel();
        txtApellidosCli = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lblRfc = new javax.swing.JLabel();
        txtRfcCli = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        lblTel = new javax.swing.JLabel();
        txtTelCli = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        lblCorreo = new javax.swing.JLabel();
        txtCorreoCli = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        lblFRegistro = new javax.swing.JLabel();
        txtFechaRCli = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        lblSueldo = new javax.swing.JLabel();
        txtSueldo = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        lblHCrediticio = new javax.swing.JLabel();
        txtHCredCli = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        btnAgregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        lblIdVrs = new javax.swing.JLabel();

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(600, 470));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAccion.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblAccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAccion.setText("Modificar Cliente");
        jPanel3.add(lblAccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 200, -1));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 10, 470));

        lblMessage.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblMessage.setForeground(new java.awt.Color(0, 193, 75));
        jPanel3.add(lblMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 450, 30));

        lblNombre.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombre.setText("Nombre:");
        jPanel3.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 110, 30));

        txtNomCli.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNomCli.setBorder(null);
        jPanel3.add(txtNomCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 240, 30));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 260, 10));

        lblApellidos.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblApellidos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblApellidos.setText("Apellidos:");
        jPanel3.add(lblApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 100, 30));

        txtApellidosCli.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtApellidosCli.setBorder(null);
        jPanel3.add(txtApellidosCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 240, 30));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 260, 10));

        lblRfc.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblRfc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRfc.setText("RFC:");
        jPanel3.add(lblRfc, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 120, 30));

        txtRfcCli.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtRfcCli.setBorder(null);
        jPanel3.add(txtRfcCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 240, 30));
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 260, 10));

        lblTel.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblTel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTel.setText("Teléfono:");
        jPanel3.add(lblTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 100, 30));

        txtTelCli.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtTelCli.setBorder(null);
        jPanel3.add(txtTelCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 240, 30));
        jPanel3.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 260, 10));

        lblCorreo.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblCorreo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCorreo.setText("Correo:");
        jPanel3.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 100, 30));

        txtCorreoCli.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtCorreoCli.setBorder(null);
        jPanel3.add(txtCorreoCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 240, 30));
        jPanel3.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 260, 10));

        lblFRegistro.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblFRegistro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFRegistro.setText("Fechade registro:");
        jPanel3.add(lblFRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 100, 30));

        txtFechaRCli.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtFechaRCli.setBorder(null);
        jPanel3.add(txtFechaRCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 240, 30));
        jPanel3.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 260, 10));

        lblSueldo.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblSueldo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSueldo.setText("Sueldo: ");
        jPanel3.add(lblSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 100, 30));

        txtSueldo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtSueldo.setBorder(null);
        jPanel3.add(txtSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 240, 30));
        jPanel3.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 260, 10));

        lblHCrediticio.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblHCrediticio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHCrediticio.setText("Historial Crediticio: ");
        jPanel3.add(lblHCrediticio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 110, 30));

        txtHCredCli.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtHCredCli.setBorder(null);
        jPanel3.add(txtHCredCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 240, 30));
        jPanel3.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 260, 10));

        btnAgregar.setBackground(new java.awt.Color(214, 5, 5));
        btnAgregar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        jPanel3.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, 90, 30));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Vendedor de piso");
        jLabel1.setToolTipText("");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 220, 50));

        txtBuscar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtBuscar.setForeground(new java.awt.Color(153, 153, 153));
        txtBuscar.setText("Introduzca algun Id para modificar un Cliente...");
        txtBuscar.setBorder(null);
        txtBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtBuscarMousePressed(evt);
            }
        });
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        jPanel3.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 330, 40));
        jPanel3.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 330, 10));

        lblIdVrs.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblIdVrs.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIdVrs.setText("Id:");
        jPanel3.add(lblIdVrs, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 110, 40));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarMousePressed
        if (txtBuscar.getText().equals("Introduzca algun Id para modificar un Cliente...")) {
            txtBuscar.setText("");
            txtBuscar.setForeground(Color.black);
        }else if(txtBuscar.getText().isEmpty()) {
            txtBuscar.setText("Introduzca algun Id para modificar un Cliente...");
            txtBuscar.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtBuscarMousePressed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed

    }//GEN-LAST:event_txtBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblAccion;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblFRegistro;
    private javax.swing.JLabel lblHCrediticio;
    private javax.swing.JLabel lblIdVrs;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRfc;
    private javax.swing.JLabel lblSueldo;
    private javax.swing.JLabel lblTel;
    private javax.swing.JTextField txtApellidosCli;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCorreoCli;
    private javax.swing.JTextField txtFechaRCli;
    private javax.swing.JTextField txtHCredCli;
    private javax.swing.JTextField txtNomCli;
    private javax.swing.JTextField txtRfcCli;
    private javax.swing.JTextField txtSueldo;
    private javax.swing.JTextField txtTelCli;
    // End of variables declaration//GEN-END:variables
}
