/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacion.vista;

/**
 *
 * @author zamud
 */
public class Page8AggFact extends javax.swing.JPanel {

    /**
     * Creates new form Page8Fact
     */
    public Page8AggFact() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        lblAccion = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblMessage = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        AggFacts = new javax.swing.JPanel();
        lblId6 = new javax.swing.JLabel();
        txtId3 = new javax.swing.JTextField();
        jSeparator39 = new javax.swing.JSeparator();
        lblNombre6 = new javax.swing.JLabel();
        txtPrecio5 = new javax.swing.JTextField();
        jSeparator40 = new javax.swing.JSeparator();
        lblTrans5 = new javax.swing.JLabel();
        txtTrans5 = new javax.swing.JTextField();
        jSeparator41 = new javax.swing.JSeparator();
        btnAgregar8 = new javax.swing.JButton();

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(600, 470));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsuario.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuario.setText("Vendedor de piso");
        lblUsuario.setToolTipText("");
        jPanel3.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 220, 50));

        lblAccion.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblAccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAccion.setText("Agregar  Factura");
        jPanel3.add(lblAccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 190, -1));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 10, 470));

        lblMessage.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblMessage.setForeground(new java.awt.Color(0, 193, 75));
        jPanel3.add(lblMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 450, 30));

        AggFacts.setBackground(new java.awt.Color(255, 255, 255));
        AggFacts.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblId6.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblId6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblId6.setText("Código de la factura:");
        AggFacts.add(lblId6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 30));

        txtId3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtId3.setBorder(null);
        AggFacts.add(txtId3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 240, 30));
        AggFacts.add(jSeparator39, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 260, 10));

        lblNombre6.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblNombre6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombre6.setText("Método de pago:");
        AggFacts.add(lblNombre6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 120, 30));

        txtPrecio5.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtPrecio5.setBorder(null);
        AggFacts.add(txtPrecio5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 240, 30));
        AggFacts.add(jSeparator40, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 260, 10));

        lblTrans5.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblTrans5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTrans5.setText("Fecha de venta:");
        AggFacts.add(lblTrans5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 120, 30));

        txtTrans5.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtTrans5.setBorder(null);
        AggFacts.add(txtTrans5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 240, 30));
        AggFacts.add(jSeparator41, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 260, 10));

        btnAgregar8.setBackground(new java.awt.Color(214, 5, 5));
        btnAgregar8.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnAgregar8.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar8.setText("Agregar");
        AggFacts.add(btnAgregar8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 90, 30));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(AggFacts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(AggFacts, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 490, 310));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AggFacts;
    private javax.swing.JButton btnAgregar8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator39;
    private javax.swing.JSeparator jSeparator40;
    private javax.swing.JSeparator jSeparator41;
    private javax.swing.JLabel lblAccion;
    private javax.swing.JLabel lblId6;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblNombre6;
    private javax.swing.JLabel lblTrans5;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtId3;
    private javax.swing.JTextField txtPrecio5;
    private javax.swing.JTextField txtTrans5;
    // End of variables declaration//GEN-END:variables
}
