/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacion.vista;

/**
 *
 * @author zamud
 */
public class Page4AggCli extends javax.swing.JPanel {

    /**
     * Creates new form Page4AggCli
     */
    public Page4AggCli() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblAccion = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblMessage = new javax.swing.JLabel();
        lblNom = new javax.swing.JLabel();
        txtNomCli = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblApellido = new javax.swing.JLabel();
        txtApellidosCli = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lblRfc = new javax.swing.JLabel();
        txtRfcCli = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        lblTel = new javax.swing.JLabel();
        txtTelCli = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        lblCorreo = new javax.swing.JLabel();
        txtCorreoCli = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        lblFRegistro = new javax.swing.JLabel();
        txtFechaRCli = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        lblSueldo = new javax.swing.JLabel();
        txtSueldo = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        lblHCrediticio = new javax.swing.JLabel();
        txtHCredCli = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        btnAgregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(600, 470));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAccion.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblAccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAccion.setText("Agregar Cliente");
        jPanel2.add(lblAccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 200, -1));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 10, 470));

        lblMessage.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblMessage.setForeground(new java.awt.Color(0, 193, 75));
        jPanel2.add(lblMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 450, 30));

        lblNom.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblNom.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNom.setText("Nombre:");
        jPanel2.add(lblNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 110, 30));

        txtNomCli.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNomCli.setBorder(null);
        jPanel2.add(txtNomCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 240, 30));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 260, 10));

        lblApellido.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblApellido.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblApellido.setText("Apellidos:");
        jPanel2.add(lblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 100, 30));

        txtApellidosCli.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtApellidosCli.setBorder(null);
        jPanel2.add(txtApellidosCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 240, 30));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 260, 10));

        lblRfc.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblRfc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRfc.setText("RFC:");
        jPanel2.add(lblRfc, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 120, 30));

        txtRfcCli.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtRfcCli.setBorder(null);
        jPanel2.add(txtRfcCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 240, 30));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 260, 10));

        lblTel.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblTel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTel.setText("Teléfono:");
        jPanel2.add(lblTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 100, 30));

        txtTelCli.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtTelCli.setBorder(null);
        jPanel2.add(txtTelCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 240, 30));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 260, 10));

        lblCorreo.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblCorreo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCorreo.setText("Correo:");
        jPanel2.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 100, 30));

        txtCorreoCli.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtCorreoCli.setBorder(null);
        jPanel2.add(txtCorreoCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 240, 30));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 260, 10));

        lblFRegistro.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblFRegistro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFRegistro.setText("Fecha de registro:");
        jPanel2.add(lblFRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 110, 30));

        txtFechaRCli.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtFechaRCli.setBorder(null);
        jPanel2.add(txtFechaRCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 240, 30));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 260, 10));

        lblSueldo.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblSueldo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSueldo.setText("Sueldo: ");
        jPanel2.add(lblSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 100, 30));

        txtSueldo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtSueldo.setBorder(null);
        jPanel2.add(txtSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 240, 30));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 260, 10));

        lblHCrediticio.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblHCrediticio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHCrediticio.setText("Historial Crediticio: ");
        jPanel2.add(lblHCrediticio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 110, 30));

        txtHCredCli.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtHCredCli.setBorder(null);
        jPanel2.add(txtHCredCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 240, 30));
        jPanel2.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 260, 10));

        btnAgregar.setBackground(new java.awt.Color(214, 5, 5));
        btnAgregar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        jPanel2.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 90, 30));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Vendedor de piso");
        jLabel1.setToolTipText("");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 220, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblAccion;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblFRegistro;
    private javax.swing.JLabel lblHCrediticio;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblNom;
    private javax.swing.JLabel lblRfc;
    private javax.swing.JLabel lblSueldo;
    private javax.swing.JLabel lblTel;
    private javax.swing.JTextField txtApellidosCli;
    private javax.swing.JTextField txtCorreoCli;
    private javax.swing.JTextField txtFechaRCli;
    private javax.swing.JTextField txtHCredCli;
    private javax.swing.JTextField txtNomCli;
    private javax.swing.JTextField txtRfcCli;
    private javax.swing.JTextField txtSueldo;
    private javax.swing.JTextField txtTelCli;
    // End of variables declaration//GEN-END:variables
}
