/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacion.vista;

/**
 *
 * @author zamud
 */
public class Page3ModifEmp extends javax.swing.JPanel {

    /**
     * Creates new form Page3Modif
     */
    public Page3ModifEmp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        lblAccion = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblMessage = new javax.swing.JLabel();
        lblIdEmp = new javax.swing.JLabel();
        txtIdEmp = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lblApellidos = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        lblNSS = new javax.swing.JLabel();
        txtNSS = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        lblCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        lblTel = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        btnModiif = new javax.swing.JButton();
        txtIdEmpM = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        lblIdEmpM = new javax.swing.JLabel();
        lblIdEmpM2 = new javax.swing.JLabel();

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(600, 470));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsuario.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuario.setText("Gerente de Recursos Humanos");
        lblUsuario.setToolTipText("");
        jPanel3.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 280, 50));

        lblAccion.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblAccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAccion.setText("Modificar Empleado");
        jPanel3.add(lblAccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 200, -1));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 10, 470));

        lblMessage.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblMessage.setForeground(new java.awt.Color(0, 193, 75));
        jPanel3.add(lblMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 450, 30));

        lblIdEmp.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblIdEmp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIdEmp.setText("Id del Empleado:");
        jPanel3.add(lblIdEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 110, 30));

        txtIdEmp.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtIdEmp.setBorder(null);
        jPanel3.add(txtIdEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 240, 30));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 260, 10));

        lblNombre.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombre.setText("Nombre:");
        lblNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 100, 30));

        txtNombre.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNombre.setBorder(null);
        jPanel3.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 240, 30));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 260, 10));

        lblApellidos.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblApellidos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblApellidos.setText("Apelilidos:");
        jPanel3.add(lblApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 120, 30));

        txtApellidos.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtApellidos.setBorder(null);
        jPanel3.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 240, 30));
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 260, 10));

        lblNSS.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblNSS.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNSS.setText("Número seguro social:");
        jPanel3.add(lblNSS, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 130, 30));

        txtNSS.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNSS.setBorder(null);
        jPanel3.add(txtNSS, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 240, 30));
        jPanel3.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 260, 10));

        lblCorreo.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblCorreo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCorreo.setText("Correo:");
        jPanel3.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 100, 30));

        txtCorreo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtCorreo.setBorder(null);
        jPanel3.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 240, 30));
        jPanel3.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 260, 10));

        lblTel.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblTel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTel.setText("Telefono:");
        jPanel3.add(lblTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 100, 30));

        txtTel.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtTel.setBorder(null);
        jPanel3.add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 240, 30));
        jPanel3.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 260, 10));

        btnModiif.setBackground(new java.awt.Color(214, 5, 5));
        btnModiif.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnModiif.setForeground(new java.awt.Color(255, 255, 255));
        btnModiif.setText("Agregar");
        jPanel3.add(btnModiif, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 90, 30));

        txtIdEmpM.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtIdEmpM.setBorder(null);
        txtIdEmpM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdEmpMActionPerformed(evt);
            }
        });
        jPanel3.add(txtIdEmpM, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 240, 30));
        jPanel3.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 260, 10));

        lblIdEmpM.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblIdEmpM.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIdEmpM.setText("a modificar:");
        jPanel3.add(lblIdEmpM, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 80, 20));

        lblIdEmpM2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblIdEmpM2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIdEmpM2.setText("Id del Empleado ");
        jPanel3.add(lblIdEmpM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 130, 20));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdEmpMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdEmpMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdEmpMActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModiif;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lblAccion;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblIdEmp;
    private javax.swing.JLabel lblIdEmpM;
    private javax.swing.JLabel lblIdEmpM2;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblNSS;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTel;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtIdEmp;
    private javax.swing.JTextField txtIdEmpM;
    private javax.swing.JTextField txtNSS;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
